"""
report_service.py — AgroVision Farmer-Facing Multi-Language Crop Condition Report Generator

Generates a simple, easy-to-understand PDF crop report for farmers in their native language
(English, Hindi, Kannada, Telugu, Tamil, Marathi, Punjabi, Bengali).
"""

import os
from datetime import datetime
from io import BytesIO
from typing import Tuple, Dict, Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# ── Register Indian Multilingual Font (Nirmala.ttc / Nirmala.ttf) ─────────────
FONT_NAME = "Helvetica"
try:
    nirmala_path = "C:\\Windows\\Fonts\\Nirmala.ttc"
    if os.path.exists(nirmala_path):
        pdfmetrics.registerFont(TTFont('Nirmala', nirmala_path, subfontIndex=0))
        pdfmetrics.registerFont(TTFont('Nirmala-Bold', nirmala_path, subfontIndex=1))
        FONT_NAME = "Nirmala"
    elif os.path.exists("C:\\Windows\\Fonts\\Nirmala.ttf"):
        pdfmetrics.registerFont(TTFont('Nirmala', "C:\\Windows\\Fonts\\Nirmala.ttf"))
        FONT_NAME = "Nirmala"
except Exception as e:
    print(f"Font registration fallback: {e}")

FONT_BOLD = f"{FONT_NAME}-Bold" if FONT_NAME == "Nirmala" else "Helvetica-Bold"


# ── Farmer Report Translations Dictionary ─────────────────────────────────────
REPORT_I18N = {
    "en": {
        "title": "🌾 AgroVision — Farmer Crop Health Report",
        "farmer": "Farmer",
        "field": "Field / Plot",
        "crop": "Crop Type",
        "area": "Area",
        "date": "Report Date",
        "verdict_healthy": "✅ CROP HEALTHY — OPTIMAL GROWTH",
        "verdict_warn": "⚠️ MONITOR FIELD — MODERATE WATER/NUTRIENT STRESS",
        "verdict_danger": "🚨 ACTION NEEDED — CROP STRESS DETECTED",
        "sec_quick_summary": "1. Simple Summary & Action Plan",
        "crop_health_title": "🌱 Crop Vegetation Health",
        "soil_moisture_title": "💧 Irrigation & Water Need",
        "fertilizer_title": "🧪 Recommended Fertilizer Dosage",
        "savings_title": "💰 Financial & Labor Savings",
        "sec_field_details": "2. Field Telemetry Details",
        "temperature": "Temperature",
        "wind_speed": "Wind Speed",
        "precipitation": "Rainfall Forecast",
        "ndvi_index": "NDVI Health Index",
        "ndwi_index": "NDWI Water Index",
        "sec_agronomist_note": "3. AI Agronomist Advice for Farmer",
        "footer_disclaimer": "Generated by AgroVision Satellite Intelligence using Sentinel-2 telemetry. Simple guidance designed for every farmer.",
        "ndvi_good": "Good green canopy. Crop is growing vigorously.",
        "ndvi_mod": "Moderate growth. Inspect field for minor nutrient deficit.",
        "ndvi_poor": "Poor biomass. Inspect field for disease or pest stress.",
        "ndwi_good": "Sufficient water. No irrigation needed today.",
        "ndwi_mod": "Slightly dry. Plan watering within 2-3 days.",
        "ndwi_poor": "Severe dryness. Irrigate today to prevent crop damage.",
        "fert_recommend": "Apply balanced Urea (45 kg/ha) + SSP (150 kg/ha) at next watering.",
        "savings_recommend": "Save approx. ₹1,450 on pump electricity & labor by avoiding unnecessary irrigation this week.",
    },
    "hi": {
        "title": "🌾 एग्रोविज़न — किसान फसल स्वास्थ्य रिपोर्ट",
        "farmer": "किसान का नाम",
        "field": "खेत का नाम",
        "crop": "फसल की किस्म",
        "area": "क्षेत्रफल",
        "date": "रिपोर्ट तिथि",
        "verdict_healthy": "✅ फसल स्वस्थ है — उत्तम विकास हो रहा है",
        "verdict_warn": "⚠️ ध्यान दें — मध्यम पानी/पोषक तत्वों की कमी",
        "verdict_danger": "🚨 तुरंत कार्रवाई करें — फसल में तनाव देखा गया",
        "sec_quick_summary": "1. मुख्य सारांश और कार्य योजना",
        "crop_health_title": "🌱 फसल की हरियाली और स्वास्थ्य",
        "soil_moisture_title": "💧 सिंचाई और पानी की आवश्यकता",
        "fertilizer_title": "🧪 अनुशंसित खाद की मात्रा",
        "savings_title": "💰 बचत और लाभ की जानकारी",
        "sec_field_details": "2. खेत की स्थिति का विवरण",
        "temperature": "तापमान",
        "wind_speed": "हवा की गति",
        "precipitation": "बारिश का अनुमान",
        "ndvi_index": "NDVI हरियाली सूचकांक",
        "ndwi_index": "NDWI नमी सूचकांक",
        "sec_agronomist_note": "3. किसान के लिए एग्रोनॉमिस्ट सलाह",
        "footer_disclaimer": "एग्रोविज़न उपग्रह बुद्धिमत्ता द्वारा निर्मित। सरल भाषा में किसान भाइयों की सहायता के लिए।",
        "ndvi_good": "फसल में अच्छी हरियाली है। विकास सामान्य है।",
        "ndvi_mod": "विकास थोड़ा कम है। खाद की आवश्यकता जांचें।",
        "ndvi_poor": "हरियाली कम है। कीट या बीमारी के लिए तुरंत निरीक्षण करें।",
        "ndwi_good": "पर्याप्त नमी है। आज पानी देने की आवश्यकता नहीं है।",
        "ndwi_mod": "हल्की सुखावट। अगले 2-3 दिनों में सिंचाई करें।",
        "ndwi_poor": "ज़्यादा सुखावट। फसल बचाने के लिए आज ही पानी दें।",
        "fert_recommend": "अगली सिंचाई पर यूरीया (45 किग्रा/हेक्टेयर) + एसएसपी दें।",
        "savings_recommend": "अनावश्यक सिंचाई रोककर इस सप्ताह पंप बिजली और मजदूरी पर लगभग ₹1,450 बचाएं।",
    },
    "kn": {
        "title": "🌾 ಅಗ್ರೋವಿಷನ್ — ರೈತರ ಬೆಳೆ ಆರೋಗ್ಯ ವರದಿ",
        "farmer": "ರೈತರ ಹೆಸರು",
        "field": "ಜಮೀನಿನ ಹೆಸರು",
        "crop": "ಬೆಳೆಯ ವಿಧ",
        "area": "ವಿಸ್ತೀರ್ಣ",
        "date": "ವರದಿ ದಿನಾಂಕ",
        "verdict_healthy": "✅ ಬೆಳೆ ಆರೋಗ್ಯಕರವಾಗಿದೆ — ಅತ್ಯುತ್ತಮ ಬೆಳವಣಿಗೆ",
        "verdict_warn": "⚠️ ಗಮನಿಸಿ — ಮಧ್ಯಮ ನೀರು ಅಥವಾ ಪೋಷಕಾಂಶ ಕೊರತೆ",
        "verdict_danger": "🚨 ತಕ್ಷಣ ಕ್ರಮ ತಗೊಳ್ಳಿ — ಬೆಳೆಯಲ್ಲಿ ತೊಂದರೆ ಕಂಡುಬಂದಿದೆ",
        "sec_quick_summary": "1. ಮುಖ್ಯ ಸಾರಾಂಶ ಮತ್ತು ಕೆಲಸದ ಯೋಜನೆ",
        "crop_health_title": "🌱 ಬೆಳೆಯ ಹಸಿರು ಮತ್ತು ಆರೋಗ್ಯ",
        "soil_moisture_title": "💧 ನೀರಾವರಿ ಮತ್ತು ನೀರಿನ ಅಗತ್ಯ",
        "fertilizer_title": "🧪 ಶಿಫಾರಸು ಮಾಡಿದ ಗೊಬ್ಬರದ ಪ್ರಮಾಣ",
        "savings_title": "💰 ಉಳಿತಾಯ ಮತ್ತು ಲಾಭದ ವಿವರ",
        "sec_field_details": "2. ಜಮೀನಿನ ಪರಿಸ್ಥಿತಿ ವಿವರಗಳು",
        "temperature": "ತಾಪಮಾನ",
        "wind_speed": "ಗಾಳಿಯ ವೇಗ",
        "precipitation": "ಮಳೆಯ ಮುನ್ಸೂಚನೆ",
        "ndvi_index": "NDVI ಹಸಿರು ಸೂಚ್ಯಂಕ",
        "ndwi_index": "NDWI ತೇವಾಂಶ ಸೂಚ್ಯಂಕ",
        "sec_agronomist_note": "3. ರೈತರಿಗಾಗಿ ಕೃಷಿ ತಜ್ಞರ ಸಲಹೆ",
        "footer_disclaimer": "ಅಗ್ರೋವಿಷನ್ ಉಪಗ್ರಹ ತಂತ್ರಜ್ಞಾನದಿಂದ ಸಿದ್ಧಪಡಿಸಲಾಗಿದೆ. ರೈತರ ಸುಲಭ ತಿಳುವಳಿಕೆಗಾಗಿ.",
        "ndvi_good": "ಬೆಳೆ ಚೆನ್ನಾಗಿ ಹಸಿರಾಗಿದೆ. ಬೆಳವಣಿಗೆ ಉತ್ತಮವಾಗಿದೆ.",
        "ndvi_mod": "ಬೆಳವಣಿಗೆ ಸ್ವಲ್ಪ ಕಡಿಮೆಯಿದೆ. ಗೊಬ್ಬರದ ಅಗತ್ಯ ಪರಿಶೀಲಿಸಿ.",
        "ndvi_poor": "ಹಸಿರು ಕಡಿಮೆಯಿದೆ. ಕೀಟ ಅಥವಾ ರೋಗದ ಬಗ್ಗೆ ತಕ್ಷಣ ಪರಿಶೀಲಿಸಿ.",
        "ndwi_good": "ಸಾಕಷ್ಟು ತೇವಾಂಶವಿದೆ. ಇಂದು ನೀರು ಹಾಯಿಸುವ ಅಗತ್ಯವಿಲ್ಲ.",
        "ndwi_mod": "ಸ್ವಲ್ಪ ಒಣಗಿದೆ. ಮುಂಬರುವ 2-3 ದಿನಗಳಲ್ಲಿ ನೀರು ಹಾಯಿಸಿ.",
        "ndwi_poor": "ಹೆಚ್ಚು ಒಣಗಿದೆ. ಬೆಳೆ ರಕ್ಷಣೆಗೆ ಇಂದೇ ನೀರು ಹಾಯಿಸಿ.",
        "fert_recommend": "ಮುಂದಿನ ನೀರಾವರಿಯೊಂದಿಗೆ ಯುರಿಯಾ (45 ಕೆಜಿ/ಹೆಕ್ಟೇರ್) ನೀಡಿ.",
        "savings_recommend": "ಅನಗತ್ಯ ನೀರಾವರಿ ತಪ್ಪಿಸಿ ಈ ವಾರ ಪಂಪ್ ಕರೆಂಟ್ ಮತ್ತು ಕೂಲಿಯಲ್ಲಿ ಸುಮಾರು ₹1,450 ಉಳಿಸಿ.",
    },
    "te": {
        "title": "🌾 అగ్రోవిజన్ — రైతు పంట ఆరోగ్య నివేదిక",
        "farmer": "రైతు పేరు",
        "field": "పొలం పేరు",
        "crop": "పంట రకం",
        "area": "విస్తీర్ణం",
        "date": "నివేదిక తేదీ",
        "verdict_healthy": "✅ పంట ఆరోగ్యంగా ఉంది — ఉత్తమ ఎదుగుదల",
        "verdict_warn": "⚠️ గమనించండి — మధ్యస్థ నీరు లేదా పోషకాల కొరత",
        "verdict_danger": "🚨 తక్షణ చర్య అవసరం — పంటలో ఒత్తిడి గుర్తించబడింది",
        "sec_quick_summary": "1. ప్రధాన సారాంశం & కార్యాచరణ ప్రణాళిక",
        "crop_health_title": "🌱 పంట పచ్చదనం & ఆరోగ్యం",
        "soil_moisture_title": "💧 నీటిపారుదల & నీటి అవసరం",
        "fertilizer_title": "🧪 సిఫార్సు చేసిన ఎరువుల మోతాదు",
        "savings_title": "💰 ఆదా & లాభాల వివరాలు",
        "sec_field_details": "2. పొలం పరిస్థితి వివరాలు",
        "temperature": "ఉష్ణోగ్రత",
        "wind_speed": "గాలి వేగం",
        "precipitation": "వర్షపాతం అంచనా",
        "ndvi_index": "NDVI పచ్చదనం సూచిక",
        "ndwi_index": "NDWI తేమ సూచిక",
        "sec_agronomist_note": "3. రైతు కోసం నిపుణుల సలహా",
        "footer_disclaimer": "అగ్రోవిజన్ ఉపగ్రహ సాంకేతికతతో తయారైంది. రైతుల సులభ అవగాహన కోసం.",
        "ndvi_good": "పంట బాగా పచ్చగా ఉంది. ఎదుగుదల బాగుంది.",
        "ndvi_mod": "ఎదుగుదల కొద్దిగా తక్కువగా ఉంది. ఎరువుల అవసరం తనిఖీ చేయండి.",
        "ndvi_poor": "పచ్చదనం తక్కువగా ఉంది. పురుగులు లేదా తెగుళ్ల కోసం వెంటనే చూడండి.",
        "ndwi_good": "తగినంత తేమ ఉంది. ఈ రోజు నీరు పెట్టనవసరం లేదు.",
        "ndwi_mod": "కొద్దిగా పొడిగా ఉంది. రాబోయే 2-3 రోజుల్లో నీరు పెట్టండి.",
        "ndwi_poor": "ఎక్కువ పొడిగా ఉంది. పంట రక్షణకు ఈ రోజే నీరు పెట్టండి.",
        "fert_recommend": "తదుపరి నీటి తడి వద్ద యూరియా (45 కేజీ/హెక్టార్) వేయండి.",
        "savings_recommend": "అవసరం లేని నీటి తడిని నివారించి ఈ వారం పంపు విద్యుత్ మరియు కూలీలపై సుమారు ₹1,450 ఆదా చేయండి.",
    },
    "ta": {
        "title": "🌾 அக்ரோவிஷன் — விவசாயி பயிர் ஆரோக்கிய அறிக்கை",
        "farmer": "விவசாயி பெயர்",
        "field": "நிலத்தின் பெயர்",
        "crop": "பயிர் வகை",
        "area": "பரப்பளவு",
        "date": "அறிக்கை தேதி",
        "verdict_healthy": "✅ பயிர் ஆரோக்கியமாக உள்ளது — சிறந்த வளர்ச்சி",
        "verdict_warn": "⚠️ கவனிக்கவும் — மிதமான நீர்/ஊட்டச்சத்து குறைபாடு",
        "verdict_danger": "🚨 உடனடியாக நடவடிக்கை எடுக்கவும் — பயிரில் பாதிப்பு",
        "sec_quick_summary": "1. முக்கிய சுருக்கம் & செயல் திட்டம்",
        "crop_health_title": "🌱 பயிர் பசுமை & ஆரோக்கியம்",
        "soil_moisture_title": "💧 நீர்ப்பாசனம் & நீர் தேவை",
        "fertilizer_title": "🧪 பரிந்துரைக்கப்பட்ட உரம் அளவு",
        "savings_title": "💰 சேமிப்பு & லாப விவரங்கள்",
        "sec_field_details": "2. நிலத்தின் விவரங்கள்",
        "temperature": "வெப்பநிலை",
        "wind_speed": "காற்றின் வேகம்",
        "precipitation": "மழை முன்னறிவிப்பு",
        "ndvi_index": "NDVI பசுமை குறியீடு",
        "ndwi_index": "NDWI ஈரப்பதம் குறியீடு",
        "sec_agronomist_note": "3. விவசாயிக்கான வேளாண் நிபுணர் ஆலோசனை",
        "footer_disclaimer": "அக்ரோவிஷன் செயற்கைக்கோள் தொழில்நுட்பத்தால் உருவாக்கப்பட்டது. விவசாயிகள் எளிதில் புரிந்துகொள்ளும் வகையில்.",
        "ndvi_good": "பயிர் நன்றாகப் பச்சையாக உள்ளது. வளர்ச்சி நன்று.",
        "ndvi_mod": "வளர்ச்சி சற்று குறைவாக உள்ளது. உரத் தேவையைச் சரிபார்க்கவும்.",
        "ndvi_poor": "பசுமை குறைவாக உள்ளது. நோய் அல்லது பூச்சித் தாக்குதலைச் சரிபார்க்கவும்.",
        "ndwi_good": "போதுமான ஈரப்பதம் உள்ளது. இன்று தண்ணீர் பாய்ச்ச தேவையில்லை.",
        "ndwi_mod": "சற்று உலர்ந்துள்ளது. அடுத்த 2-3 நாட்களில் தண்ணீர் பாய்ச்சவும்.",
        "ndwi_poor": "அதிக உலர்வாக உள்ளது. பயிரைப் பாதுகாக்க இன்றே தண்ணீர் பாய்ச்சவும்.",
        "fert_recommend": "அடுத்த நீர்ப்பாசனத்தின் போது யூரியா (45 கிலோ/ஹெக்டேர்) இடவும்.",
        "savings_recommend": "தேவையற்ற நீர்ப்பாசனத்தைத் தவிர்த்து இந்த வாரம் பம்ப் மின்சாரம் மற்றும் கூலியில் சுமார் ₹1,450 சேமிக்கவும்.",
    },
    "mr": {
        "title": "🌾 ॲग्रोव्हिजन — शेतकरी पीक आरोग्य अहवाल",
        "farmer": "शेतकऱ्याचे नाव",
        "field": "शेताचे नाव",
        "crop": "पिकाचा प्रकार",
        "area": "क्षेत्रफळ",
        "date": "अहवाल तारीख",
        "verdict_healthy": "✅ पीक निरोगी आहे — उत्तम वाढ होत आहे",
        "verdict_warn": "⚠️ लक्ष द्या — मध्यम पाणी/पोषक तत्वांची कमतरता",
        "verdict_danger": "🚨 तातडीने कारवाई करा — पिकावर ताण दिसून येत आहे",
        "sec_quick_summary": "1. मुख्य सारांश आणि कृती योजना",
        "crop_health_title": "🌱 पिकाची हिरवळ आणि आरोग्य",
        "soil_moisture_title": "💧 सिंचन आणि पाण्याची गरज",
        "fertilizer_title": "🧪 शिफारस केलेली खत मात्रा",
        "savings_title": "💰 बचत आणि फायद्याची माहिती",
        "sec_field_details": "2. शेतातील परिस्थितीचा तपशील",
        "temperature": "तापमान",
        "wind_speed": "वाऱ्याचा वेग",
        "precipitation": "पावसाचा अंदाज",
        "ndvi_index": "NDVI हिरवळ निर्देशांक",
        "ndwi_index": "NDWI ओलावा निर्देशांक",
        "sec_agronomist_note": "3. शेतकऱ्यांसाठी तज्ज्ञ सल्ला",
        "footer_disclaimer": "ॲग्रोव्हिजन उपग्रह तंत्रज्ञानाद्वारे निर्मित. सोप्या भाषेत शेतकऱ्यांच्या मदतीसाठी.",
        "ndvi_good": "पिकामध्ये उत्तम हिरवळ आहे. वाढ छान आहे.",
        "ndvi_mod": "वाढ थोडी कमी आहे. खताची गरज तपासा.",
        "ndvi_poor": "हिरवळ कमी आहे. कीड किंवा रोगासाठी त्वरित पाहणी करा.",
        "ndwi_good": "पुरेसा ओलावा आहे. आज पाणी देण्याची गरज नाही.",
        "ndwi_mod": "थोडं कोरडं आहे. पुढील 2-3 दिवसांत पाणी द्या.",
        "ndwi_poor": "जास्त कोरडेपणा. पीक वाचवण्यासाठी आजच पाणी द्या.",
        "fert_recommend": "पुढील पाण्यासोबत युरिया (45 किलो/हेक्टर) द्या.",
        "savings_recommend": "अनावश्यक सिंचन टाळून या आठवड्यात पंप वीज आणि मजुरीवर सुमारे ₹1,450 वाचवा.",
    },
    "pa": {
        "title": "🌾 ਐਗਰੋਵਿਜ਼ਨ — ਕਿਸਾਨ ਫਸਲ ਸਿਹਤ ਰਿਪੋਰਟ",
        "farmer": "ਕਿਸਾਨ ਦਾ ਨਾਮ",
        "field": "ਖੇਤ ਦਾ ਨਾਮ",
        "crop": "ਫਸਲ ਦੀ ਕਿਸਮ",
        "area": "ਖੇਤਰਫਲ",
        "date": "ਰਿਪੋਰਟ ਮਿਤੀ",
        "verdict_healthy": "✅ ਫਸਲ ਸਿਹਤਮੰਦ ਹੈ — ਵਧੀਆ ਵਾਧਾ ਹੋ ਰਿਹਾ ਹੈ",
        "verdict_warn": "⚠️ ਧਿਆਨ ਦਿਓ — ਦਰਮਿਆਨਾ ਪਾਣੀ/ਖੁਰਾਕ ਦੀ ਘਾਟ",
        "verdict_danger": "🚨 ਤੁਰੰਤ ਕਾਰਵਾਈ ਕਰੋ — ਫਸਲ ਵਿੱਚ ਤਣਾਅ ਦੇਖਿਆ ਗਿਆ",
        "sec_quick_summary": "1. ਮੁੱਖ ਸਾਰਾਂਸ਼ ਅਤੇ ਕਾਰਜ ਯੋਜਨਾ",
        "crop_health_title": "🌱 ਫਸਲ ਦੀ ਹਰਿਆਵਲ ਅਤੇ ਸਿਹਤ",
        "soil_moisture_title": "💧 ਸਿੰਚਾਈ ਅਤੇ ਪਾਣੀ ਦੀ ਲੋੜ",
        "fertilizer_title": "🧪 ਸਿਫਾਰਸ਼ ਕੀਤੀ ਖਾਦ ਦੀ ਮਾਤਰਾ",
        "savings_title": "💰 ਬਚਤ ਅਤੇ ਲਾਭ ਦੀ ਜਾਣਕਾਰੀ",
        "sec_field_details": "2. ਖੇਤ ਦੀ ਸਥਿਤੀ ਦਾ ਵੇਰਵਾ",
        "temperature": "ਤਾਪਮਾਨ",
        "wind_speed": "ਹਵਾ ਦੀ ਗਤੀ",
        "precipitation": "ਮੀਂਹ ਦਾ ਅਨੁਮਾਨ",
        "ndvi_index": "NDVI ਹਰਿਆਵਲ ਸੂਚਕਾਂਕ",
        "ndwi_index": "NDWI ਨਮੀ ਸੂਚਕਾਂਕ",
        "sec_agronomist_note": "3. ਕਿਸਾਨਾਂ ਲਈ ਖੇਤੀਬਾੜੀ ਮਾਹਿਰ ਦੀ ਸਲਾਹ",
        "footer_disclaimer": "ਐਗਰੋਵਿਜ਼ਨ ਸੈਟੇਲਾਈਟ ਤਕਨਾਲੋਜੀ ਦੁਆਰਾ ਤਿਆਰ ਕੀਤਾ ਗਿਆ। ਕਿਸਾਨਾਂ ਦੀ ਸੌਖੀ ਸਮਝ ਲਈ।",
        "ndvi_good": "ਫਸਲ ਬਹੁਤ ਵਧੀਆ ਹਰੀ ਹੈ। ਵਾਧਾ ਆਮ ਹੈ।",
        "ndvi_mod": "ਵਾਧਾ ਥੋੜ੍ਹਾ ਘੱਟ ਹੈ। ਖਾਦ ਦੀ ਲੋੜ ਚੈੱਕ ਕਰੋ।",
        "ndvi_poor": "ਹਰਿਆਵਲ ਘੱਟ ਹੈ। ਕੀੜੇ ਜਾਂ ਬੀਮਾਰੀ ਲਈ ਤੁਰੰਤ ਦੇਖੋ।",
        "ndwi_good": "ਪੂਰੀ ਨਮੀ ਹੈ। ਅੱਜ ਪਾਣੀ ਲਾਉਣ ਦੀ ਲੋੜ ਨਹੀਂ।",
        "ndwi_mod": "ਥੋੜ੍ਹਾ ਸੁੱਕਾ ਹੈ। ਅਗਲੇ 2-3 ਦਿਨਾਂ ਵਿੱਚ ਪਾਣੀ ਲਾਓ।",
        "ndwi_poor": "ਬਹੁਤ ਸੁੱਕਾ ਹੈ। ਫਸਲ ਬਚਾਉਣ ਲਈ ਅੱਜ ਹੀ ਪਾਣੀ ਲਾਓ।",
        "fert_recommend": "ਅਗਲੇ ਪਾਣੀ ਨਾਲ ਯੂਰੀਆ (45 ਕਿਲੋ/ਹੈਕਟੇਅਰ) ਪਾਓ।",
        "savings_recommend": "ਵਾਧੂ ਸਿੰਚਾਈ ਰੋਕ ਕੇ ਇਸ ਹਫ਼ਤੇ ਮੋਟਰ ਬਿਜਲੀ ਅਤੇ ਮਜ਼ਦੂਰੀ ਦੇ ਲਗਭਗ ₹1,450 ਬਚਾਓ।",
    },
    "bn": {
        "title": "🌾 অ্যাগ্রোভিশন — কৃষক ফসলের স্বাস্থ্য রিপোর্ট",
        "farmer": "কৃষকের নাম",
        "field": "জমির নাম",
        "crop": "ফসলের ধরন",
        "area": "ক্ষেত্রফল",
        "date": "রিপোর্টের তারিখ",
        "verdict_healthy": "✅ ফসল স্বাস্থ্যকর — চমৎকার বৃদ্ধি হচ্ছে",
        "verdict_warn": "⚠️ সতর্ক থাকুন — মাঝারি জল/পুষ্টির ঘাটতি",
        "verdict_danger": "🚨 অবিলম্বে পদক্ষেপ নিন — ফসলে সমস্যা দেখা গেছে",
        "sec_quick_summary": "1. মূল সারসংক্ষেপ ও কাজের পরিকল্পনা",
        "crop_health_title": "🌱 ফসলের সবুজ সতেজতা ও স্বাস্থ্য",
        "soil_moisture_title": "💧 সেচ ও জলের প্রয়োজনীয়তা",
        "fertilizer_title": "🧪 সুপারিশকৃত সারের পরিমাণ",
        "savings_title": "💰 সাশ্রয় ও লাভের বিবরণ",
        "sec_field_details": "2. জমির অবস্থার বিবরণ",
        "temperature": "তাপমাত্রা",
        "wind_speed": "বাতাসের গতি",
        "precipitation": "বৃষ্টিপাতের পূর্বাভাস",
        "ndvi_index": "NDVI সতেজতা সূচক",
        "ndwi_index": "NDWI আর্দ্রতা সূচক",
        "sec_agronomist_note": "3. কৃষকদের জন্য কৃষি বিশেষজ্ঞদের পরামর্শ",
        "footer_disclaimer": "অ্যাগ্রোভিশন উপগ্রহ প্রযুক্তি দ্বারা নির্মিত। কৃষকদের সহজে বোঝার জন্য।",
        "ndvi_good": "ফসল চমৎকার সবুজ ও সতেজ। বৃদ্ধি স্বাভাবিক।",
        "ndvi_mod": "বৃদ্ধি কিছুটা কম। সারের প্রয়োজন পরীক্ষা করুন।",
        "ndvi_poor": "সবুজ ভাব কম। পোকা বা রোগের জন্য অবিলম্বে পরিদর্শন করুন।",
        "ndwi_good": "পর্যাপ্ত আর্দ্রতা আছে। আজ জল দেওয়ার প্রয়োজন নেই।",
        "ndwi_mod": "কিছুটা শুষ্ক। আগামী ২-৩ দিনের মধ্যে সেচ দিন।",
        "ndwi_poor": "অত্যধিক শুষ্ক। ফসল বাঁচাতে আজই সেচ দিন।",
        "fert_recommend": "পরবর্তী সেচের সাথে ইউরিয়া (৪৫ কেজি/হেক্টর) প্রয়োগ করুন।",
        "savings_recommend": "অপ্রয়োজনীয় সেচ এড়িয়ে এই সপ্তাহে পাম্পের বিদ্যুৎ ও মজুরির প্রায় ₹১,৪৫০ সাশ্রয় করুন।",
    }
}


def get_report_dict(lang: str) -> Dict[str, str]:
    return REPORT_I18N.get(lang, REPORT_I18N["en"])


def build_crop_report_pdf(field_data: Dict[str, Any], lang: str = "en") -> bytes:
    """
    Builds a plain-language PDF crop report localized to farmer's language.
    """
    txt = get_report_dict(lang)

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=1.5 * cm, bottomMargin=1.5 * cm,
        leftMargin=1.8 * cm, rightMargin=1.8 * cm,
    )

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="ReportTitle", fontSize=18, leading=22, spaceAfter=4,
        fontName=FONT_BOLD, textColor=colors.HexColor("#064e3b")
    ))
    styles.add(ParagraphStyle(
        name="SubTitle", fontSize=10, leading=14, textColor=colors.HexColor("#475569"),
        fontName=FONT_NAME, spaceAfter=14
    ))
    styles.add(ParagraphStyle(
        name="SectionHead", fontSize=12, leading=16, spaceBefore=14, spaceAfter=6,
        fontName=FONT_BOLD, textColor=colors.HexColor("#065f46")
    ))
    styles.add(ParagraphStyle(
        name="VerdictBig", fontSize=14, leading=18, fontName=FONT_BOLD,
        alignment=TA_CENTER, textColor=colors.white
    ))
    styles.add(ParagraphStyle(
        name="CardHeader", fontSize=11, leading=15, fontName=FONT_BOLD,
        textColor=colors.HexColor("#0f172a")
    ))
    styles.add(ParagraphStyle(
        name="CardBody", fontSize=10, leading=14, fontName=FONT_NAME,
        textColor=colors.HexColor("#334155")
    ))

    report_date = field_data.get("report_date", datetime.now())
    ndvi = float(field_data.get("ndvi") if field_data.get("ndvi") is not None else 0.0)
    ndwi = float(field_data.get("ndwi") if field_data.get("ndwi") is not None else 0.0)

    # Status verdict logic
    if ndvi >= 0.6 and ndwi >= 0.2:
        verdict_text = txt["verdict_healthy"]
        verdict_color = colors.HexColor("#059669")
    elif ndvi >= 0.35 or ndwi >= 0.05:
        verdict_text = txt["verdict_warn"]
        verdict_color = colors.HexColor("#d97706")
    else:
        verdict_text = txt["verdict_danger"]
        verdict_color = colors.HexColor("#dc2626")

    story = []

    # --- Header -------------------------------------------------------
    story.append(Paragraph(txt["title"], styles["ReportTitle"]))
    farmer_str = str(field_data.get('farmer_name', 'Farmer'))
    field_str = str(field_data.get('field_name', 'Primary Field'))
    crop_str = str(field_data.get('crop_type', 'General Agriculture'))
    date_str = report_date.strftime('%d %b %Y, %I:%M %p')

    story.append(Paragraph(
        f"{txt['field']}: <b>{field_str}</b> &nbsp;|&nbsp; "
        f"{txt['farmer']}: <b>{farmer_str}</b> &nbsp;|&nbsp; "
        f"{txt['crop']}: <b>{crop_str}</b> &nbsp;|&nbsp; "
        f"{txt['date']}: <b>{date_str}</b>",
        styles["SubTitle"]
    ))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#10b981"), thickness=1.5))
    story.append(Spacer(1, 10))

    # --- Verdict Banner -----------------------------------------------
    verdict_table = Table(
        [[Paragraph(verdict_text, styles["VerdictBig"])]],
        colWidths=[doc.width]
    )
    verdict_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), verdict_color),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(verdict_table)
    story.append(Spacer(1, 14))

    # --- SECTION 1: Simple Summary & Action Cards -----------------------
    story.append(Paragraph(txt["sec_quick_summary"], styles["SectionHead"]))

    # Card 1: Crop Health
    ndvi_msg = txt["ndvi_good"] if ndvi >= 0.6 else (txt["ndvi_mod"] if ndvi >= 0.35 else txt["ndvi_poor"])
    card1 = [
        Paragraph(txt["crop_health_title"], styles["CardHeader"]),
        Paragraph(ndvi_msg, styles["CardBody"])
    ]

    # Card 2: Water Need
    ndwi_msg = txt["ndwi_good"] if ndwi >= 0.2 else (txt["ndwi_mod"] if ndwi >= 0.05 else txt["ndwi_poor"])
    card2 = [
        Paragraph(txt["soil_moisture_title"], styles["CardHeader"]),
        Paragraph(ndwi_msg, styles["CardBody"])
    ]

    # Card 3: Fertilizer
    card3 = [
        Paragraph(txt["fertilizer_title"], styles["CardHeader"]),
        Paragraph(txt["fert_recommend"], styles["CardBody"])
    ]

    # Card 4: Rupee Savings
    card4 = [
        Paragraph(txt["savings_title"], styles["CardHeader"]),
        Paragraph(txt["savings_recommend"], styles["CardBody"])
    ]

    grid_data = [
        [card1, card2],
        [card3, card4]
    ]

    summary_grid = Table(grid_data, colWidths=[doc.width * 0.49, doc.width * 0.49])
    summary_grid.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#f0fdf4")),
        ("BACKGROUND", (1, 0), (1, 0), colors.HexColor("#eff6ff")),
        ("BACKGROUND", (0, 1), (0, 1), colors.HexColor("#fefce8")),
        ("BACKGROUND", (1, 1), (1, 1), colors.HexColor("#fdf2f8")),
        ("BOX", (0, 0), (0, 0), 1, colors.HexColor("#bbf7d0")),
        ("BOX", (1, 0), (1, 0), 1, colors.HexColor("#bfdbfe")),
        ("BOX", (0, 1), (0, 1), 1, colors.HexColor("#fef08a")),
        ("BOX", (1, 1), (1, 1), 1, colors.HexColor("#fbcfe8")),
        ("PADDING", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(summary_grid)
    story.append(Spacer(1, 14))

    # --- SECTION 2: Field Details Table ---------------------------------
    story.append(Paragraph(txt["sec_field_details"], styles["SectionHead"]))
    lat_val = field_data.get("latitude")
    lon_val = field_data.get("longitude")
    coord_str = f"{lat_val:.4f}°, {lon_val:.4f}°" if lat_val is not None and lon_val is not None else "N/A"

    details_rows = [
        [txt["crop"], str(field_data.get("crop_type", "Wheat"))],
        [txt["area"], f"{field_data.get('area_hectares', '1.5')} Hectares"],
        ["Location Coords", coord_str],
        [txt["ndvi_index"], f"{ndvi:.4f}"],
        [txt["ndwi_index"], f"{ndwi:.4f}"],
        [txt["temperature"], f"{field_data.get('temperature_c', '24')} °C"],
        [txt["wind_speed"], f"{field_data.get('windspeed_kmh', '10')} km/h"],
        [txt["precipitation"], f"{field_data.get('rainfall_mm_forecast', '0.0')} mm"],
    ]
    dt_table = Table(details_rows, colWidths=[doc.width * 0.45, doc.width * 0.55])
    dt_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), FONT_BOLD),
        ("FONTNAME", (1, 0), (1, -1), FONT_NAME),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("LINEBELOW", (0, 0), (-1, -2), 0.5, colors.HexColor("#e2e8f0")),
    ]))
    story.append(dt_table)
    story.append(Spacer(1, 14))

    # --- SECTION 3: AI & Agronomist Advice -------------------------------
    story.append(Paragraph(txt["sec_agronomist_note"], styles["SectionHead"]))
    rec_text = str(field_data.get("ml_recommendation", "Continue standard crop care and monitor soil moisture."))
    story.append(Paragraph(rec_text, ParagraphStyle(name="NoteBody", fontSize=10, leading=15, fontName=FONT_NAME, textColor=colors.HexColor("#1e293b"))))

    # --- Footer --------------------------------------------------------
    story.append(Spacer(1, 18))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#cbd5e1"), thickness=1))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        txt["footer_disclaimer"],
        ParagraphStyle(name="FooterText", fontSize=8, leading=11, fontName=FONT_NAME, textColor=colors.HexColor("#64748b"), alignment=TA_CENTER)
    ))

    doc.build(story)
    return buffer.getvalue()
