import React, { createContext, useContext, useState, useEffect } from 'react';

// ── Supported Languages Definition ──────────────────────────────────────────
export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi', native: 'हिंदी', flag: '🇮🇳' },
  { code: 'kn', label: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'mr', label: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { code: 'pa', label: 'Punjabi', native: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা', flag: '🇮🇳' },
];

// ── Translations Dictionary ──────────────────────────────────────────────────
const TRANSLATIONS = {
  en: {
    // Nav & General
    appTitle: 'AgroVision',
    subtitle: 'Satellite Intelligence',
    liveMap: '🛰️ Live Satellite Map',
    fieldManager: '🌾 Field Manager',
    cropDoctor: '🔬 AI Crop Doctor',
    quickGuide: '📖 Quick Guide',
    street: 'Street',
    satellite: 'Satellite',
    cropReport: 'Crop Report',
    downloading: 'Generating...',
    live: 'LIVE',
    offline: 'OFFLINE',
    logout: 'Logout',
    guest: 'Guest',

    // Dashboard HUD
    dashboardHeader: '🌾 FIELD INTELLIGENCE DASHBOARD',
    dashboardSubtitle: 'Click map to scan · Draw polygons to save fields',
    scanning: 'Scanning...',
    sysNominal: 'sys:nominal',
    telemetryTitle: '📊 Telemetry & Analysis',
    primaryScan: 'PRIMARY SCAN (NDVI)',
    sessionMetrics: 'SESSION METRICS',
    scanHistory: 'SCAN HISTORY',

    // Field Manager
    fieldsRegistered: 'fields registered',
    drawNewField: 'Draw New Field Polygon',
    noFieldsYet: 'No fields registered yet',
    noFieldsDesc: 'Click "Draw New Field Polygon" and trace your field boundary on the map',
    totalArea: 'Total Area',
    avgNdvi: 'Avg NDVI',
    fieldsCount: 'Fields',
    statusStressed: 'Stressed',
    statusModerate: 'Moderate',
    statusHealthy: 'Healthy',
    statusExcellent: 'Excellent',
    statusNoData: 'No Data',
    sownOn: 'Sown',

    // Crop Doctor Page
    cropDoctorTitle: '🔬 AI Crop Doctor & Disease Diagnostic Hub',
    cropDoctorSubtitle: 'Upload crop leaf photo for automated pathogen diagnosis, health scoring, NPK fertilizer dosage, & growing suitability.',
    uploadPhotoBtn: 'Upload Leaf Photo',
    leafScannerTitle: 'Leaf Image Scanner',
    noImageLoaded: 'No Image Loaded',
    noImageDesc: 'Select a sample leaf below or upload your crop photo to trigger analysis.',
    dropzoneTitle: 'Drop crop leaf photo here or Browse',
    dropzoneSub: 'Supports PNG, JPG, WEBP, HEIC',
    samplePresetsTitle: '🧪 Try Sample Crop Presets',
    sampleRice: '🌾 Rice Leaf Blast',
    sampleWheat: '🍂 Wheat Yellow Rust',
    sampleCorn: '🐛 Corn Stem Borer',
    sampleSugarcane: '🌱 Healthy Sugarcane',
    emptyRevealTitle: 'Upload Leaf Photo to Reveal Diagnostic Analysis',
    emptyRevealDesc: 'Drag & drop a crop leaf image on the left or select a sample preset. AgroVision AI will extract color & lesion features, calculate crop health index, identify disease pathogens, and provide tailored NPK fertilizer & soil suitability guidance.',
    selectFileToScan: 'Select Photo File to Scan',
    pathogenResultTitle: 'Pathogen Diagnostic Results',
    cropHealthIndex: 'Crop Health Index',
    diagnosisConfidence: 'Diagnosis Confidence',
    affectedLeafArea: 'Affected Leaf Area',
    symptomsObserved: 'Symptoms Observed',
    npkGuideTitle: 'Recommended Fertilizers & NPK Nutrition Guide',
    npkTarget: 'NPK Formulation Target',
    soilGuideTitle: 'Soil, Climate & Growing Region Suitability Guide',
    idealSoilPh: '🌱 Ideal Soil & pH Range',
    tempRainfall: '🌤️ Temperature & Rainfall',
    optimalPh: 'Optimal Soil pH',
    annualRainfall: 'Annual Rainfall',
    growingRegions: '📍 Major Suitable Growing Regions in India:',
    carePlanTitle: 'Recommended Treatment & Care Plan',
    organicRemedy: '🌿 Organic Remedy',
    chemicalTreatment: '🧪 Chemical Treatment',

    // Save field modal
    saveFieldTitle: '🌾 Save New Field Polygon',
    fieldNameLabel: 'Field Name *',
    cropTypeLabel: 'Crop Type',
    sowingDateLabel: 'Sowing Date',
    areaLabel: 'Area (hectares)',
    saveBtn: '✓ Save Field',
    cancelBtn: 'Cancel',

    // Farmer Guide
    guideTitle: '📖 How to Use AgroVision — Farmer Guide',
    guideSubtitle: 'Follow these simple steps to monitor your crops using satellite intelligence',
    guideStep1Title: '1. Click on the Map',
    guideStep1Desc: 'Tap any location on the satellite map to instantly get NDVI vegetation health, temperature, soil moisture and rainfall data for that spot.',
    guideStep2Title: '2. Draw Your Field',
    guideStep2Desc: 'Click Field Manager → Draw New Field Polygon and trace your farm boundary on the map. Your field is saved with its area and crop type.',
    guideStep3Title: '3. Read the NDVI Value',
    guideStep3Desc: 'NDVI 0.6–1.0 = healthy green crops. 0.2–0.5 = moderate. Below 0.2 = poor vegetation or bare soil. Use this weekly to track crop health.',
    guideStep4Title: '4. Upload a Leaf Photo',
    guideStep4Desc: 'Go to the AI Crop Doctor tab and upload a photo of a sick leaf. The AI detects the disease and suggests organic and chemical treatments.',
    guideStep5Title: '5. Download Crop Report',
    guideStep5Desc: 'After scanning, tap Download Crop Report to get a full PDF with NDVI, soil, weather data and recommendations — share it with your agronomist.',
    guideStep6Title: '6. Switch Language',
    guideStep6Desc: 'Tap the language button at the top to read everything in Hindi, Kannada, Telugu, Tamil, Marathi, Punjabi or Bengali.',
    guideTip: '💡 Tip: Scan your field every week during the growing season to catch problems early!',
  },

  hi: {
    // Nav & General
    appTitle: 'एग्रोविज़न',
    subtitle: 'सैटेलाइट इंटेलिजेंस',
    liveMap: '🛰️ लाइव सैटेलाइट मानचित्र',
    fieldManager: '🌾 खेत प्रबंधक',
    cropDoctor: '🔬 AI फसल डॉक्टर',
    quickGuide: '📖 त्वरित गाइड',
    street: 'सड़क',
    satellite: 'सैटेलाइट',
    cropReport: 'फसल रिपोर्ट',
    downloading: 'रिपोर्ट बन रही है...',
    live: 'लाइव',
    offline: 'ऑफलाइन',
    logout: 'लॉगआउट',
    guest: 'अतिथि',

    // Dashboard HUD
    dashboardHeader: '🌾 खेत सूचना डैशबोर्ड',
    dashboardSubtitle: 'स्कैन करने के लिए नक्शे पर क्लिक करें · खेत सहेजने के लिए बहुभुज बनाएं',
    scanning: 'स्कैन हो रहा है...',
    sysNominal: 'सिस्टम: सामान्य',
    telemetryTitle: '📊 टेलीमेट्री और विश्लेषण',
    primaryScan: 'प्राथमिक स्कैन (NDVI)',
    sessionMetrics: 'सत्र मीट्रिक',
    scanHistory: 'स्कैन इतिहास',

    // Field Manager
    fieldsRegistered: 'खेत पंजीकृत हैं',
    drawNewField: 'नया खेत सीमांकन करें',
    noFieldsYet: 'कोई खेत पंजीकृत नहीं है',
    noFieldsDesc: 'ऊपर "नया खेत सीमांकन करें" पर क्लिक करें और नक्शे पर सीमा बनाएं',
    totalArea: 'कुल क्षेत्रफल',
    avgNdvi: 'औसत NDVI',
    fieldsCount: 'कुल खेत',
    statusStressed: 'तनावग्रस्त',
    statusModerate: 'मध्यम',
    statusHealthy: 'स्वस्थ',
    statusExcellent: 'उत्कृष्ट',
    statusNoData: 'कोई डेटा नहीं',
    sownOn: 'बुआई',

    // Crop Doctor Page
    cropDoctorTitle: '🔬 AI फसल डॉक्टर और रोग निदान केंद्र',
    cropDoctorSubtitle: 'रोगज़नक़ निदान, स्वास्थ्य स्कोर, NPK उर्वरक खुराक और फसल उपयुक्तता के लिए पत्ती की फोटो अपलोड करें।',
    uploadPhotoBtn: 'पत्ती की फोटो अपलोड करें',
    leafScannerTitle: 'पत्ती छवि स्कैनर',
    noImageLoaded: 'कोई छवि लोड नहीं की गई',
    noImageDesc: 'विश्लेषण शुरू करने के लिए नीचे नमूना चुनें या फोटो अपलोड करें।',
    dropzoneTitle: 'यहाँ फसल की पत्ती की फोटो छोड़ें या ब्राउज़ करें',
    dropzoneSub: 'PNG, JPG, WEBP, HEIC प्रारूप समर्थित हैं',
    samplePresetsTitle: '🧪 नमूना फसल पत्तियां आज़माएं',
    sampleRice: '🌾 धान का झुलसा रोग (Leaf Blast)',
    sampleWheat: '🍂 गेहूं का पीला रतुआ (Yellow Rust)',
    sampleCorn: '🐛 मक्का तना छेदक (Stem Borer)',
    sampleSugarcane: '🌱 स्वस्थ गन्ना (Healthy)',
    emptyRevealTitle: 'रोग निदान विश्लेषण देखने के लिए पत्ती की फोटो अपलोड करें',
    emptyRevealDesc: 'बाईं ओर पत्ती की छवि अपलोड करें या नमूना चुनें। एग्रोविज़न AI रंग और घाव के लक्षणों का विश्लेषण करके स्वास्थ्य स्कोर, बीमारी का नाम और NPK उर्वरक सलाह देगा।',
    selectFileToScan: 'स्कैन के लिए फोटो चुनें',
    pathogenResultTitle: 'रोगज़नक़ निदान परिणाम',
    cropHealthIndex: 'फसल स्वास्थ्य सूचकांक',
    diagnosisConfidence: 'निदान सटीकता',
    affectedLeafArea: 'प्रभावित पत्ती क्षेत्र',
    symptomsObserved: 'देखे गए लक्षण',
    npkGuideTitle: 'अनुशंसित उर्वरक और NPK पोषण गाइड',
    npkTarget: 'NPK संतुलित मात्रा',
    soilGuideTitle: 'मिट्टी, जलवायु और उपयुक्त क्षेत्र गाइड',
    idealSoilPh: '🌱 आदर्श मिट्टी और pH सीमा',
    tempRainfall: '🌤️ तापमान और वर्षा',
    optimalPh: 'इष्टतम मिट्टी pH',
    annualRainfall: 'वार्षिक वर्षा',
    growingRegions: '📍 भारत में प्रमुख उपयुक्त फसल क्षेत्र:',
    carePlanTitle: 'अनुशंसित उपचार और देखभाल योजना',
    organicRemedy: '🌿 जैविक उपचार (Organic)',
    chemicalTreatment: '🧪 रासायनिक उपचार (Chemical)',

    // Save field modal
    saveFieldTitle: '🌾 नया खेत सहेजें',
    fieldNameLabel: 'खेत का नाम *',
    cropTypeLabel: 'फसल का प्रकार',
    sowingDateLabel: 'बुआई की तारीख',
    areaLabel: 'क्षेत्रफल (हेक्टेयर)',
    saveBtn: '✓ खेत सहेजें',
    cancelBtn: 'रद्द करें',

    // Farmer Guide
    guideTitle: '📖 एग्रोविज़न का उपयोग कैसे करें — किसान गाइड',
    guideSubtitle: 'सैटेलाइट तकनीक से अपनी फसल की निगरानी के लिए इन सरल चरणों का पालन करें',
    guideStep1Title: '1. नक्शे पर क्लिक करें',
    guideStep1Desc: 'किसी भी स्थान पर क्लिक करें — NDVI वनस्पति स्वास्थ्य, तापमान, मिट्टी की नमी और वर्षा की जानकारी तुरंत पाएं।',
    guideStep2Title: '2. अपना खेत बनाएं',
    guideStep2Desc: 'खेत प्रबंधक → नया खेत सीमांकन करें पर क्लिक करें और नक्शे पर अपने खेत की सीमा बनाएं।',
    guideStep3Title: '3. NDVI मान पढ़ें',
    guideStep3Desc: 'NDVI 0.6–1.0 = स्वस्थ हरी फसल। 0.2–0.5 = मध्यम। 0.2 से कम = कमजोर वनस्पति या नंगी मिट्टी।',
    guideStep4Title: '4. पत्ती की फोटो अपलोड करें',
    guideStep4Desc: 'AI फसल डॉक्टर टैब पर जाएं और बीमार पत्ती की फोटो अपलोड करें। AI रोग पहचानकर जैविक और रासायनिक उपाय बताएगा।',
    guideStep5Title: '5. फसल रिपोर्ट डाउनलोड करें',
    guideStep5Desc: 'स्कैन के बाद फसल रिपोर्ट डाउनलोड करें और NDVI, मिट्टी, मौसम तथा सुझावों वाली PDF रिपोर्ट पाएं।',
    guideStep6Title: '6. भाषा बदलें',
    guideStep6Desc: 'ऊपर भाषा बटन दबाएं और हिंदी, कन्नड़, तेलुगू, तमिल, मराठी, पंजाबी या बांग्ला में पढ़ें।',
    guideTip: '💡 सुझाव: फसल मौसम में हर हफ्ते खेत स्कैन करें — समस्याएं जल्दी पकड़ में आएंगी!',
  },

  kn: {
    // Nav & General
    appTitle: 'ಅಗ್ರೋವಿಷನ್',
    subtitle: 'ಉಪಗ್ರಹ ಬುದ್ಧಿವಂತಿಕೆ',
    liveMap: '🛰️ ನೇರ ಉಪಗ್ರಹ ನಕ್ಷೆ',
    fieldManager: '🌾 ಜಮೀನು ನಿರ್ವಾಹಕ',
    cropDoctor: '🔬 AI ಬೆಳೆ ವೈದ್ಯ',
    quickGuide: '📖 ತ್ವರಿತ ಮಾರ್ಗದರ್ಶಿ',
    street: 'ರಸ್ತೆ',
    satellite: 'ಉಪಗ್ರಹ',
    cropReport: 'ಬೆಳೆ ವರದಿ',
    downloading: 'ವರದಿ ಸಿದ್ಧವಾಗುತ್ತಿದೆ...',
    live: 'ಲೈವ್',
    offline: 'ಆಫ್‌ಲೈನ್',
    logout: 'ನಿರ್ಗಮಿಸಿ (Logout)',
    guest: 'ಅತಿಥಿ',

    // Dashboard HUD
    dashboardHeader: '🌾 ಜಮೀನು ಮಾಹಿತಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    dashboardSubtitle: 'ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ನಕ್ಷೆಯನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿ · ಜಮೀನು ಉಳಿಸಲು ರೇಖಾಚಿತ್ರ ಬಿಡಿಸಿ',
    scanning: 'ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    sysNominal: 'ವ್ಯವಸ್ಥೆ: ಸಾಮಾನ್ಯ',
    telemetryTitle: '📊 ಟೆಲಿಮೆಟ್ರಿ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ',
    primaryScan: 'ಪ್ರಾಥಮಿಕ ಸ್ಕ್ಯಾನ್ (NDVI)',
    sessionMetrics: 'ಸೆಷನ್ ಮಾಪನಗಳು',
    scanHistory: 'ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸ',

    // Field Manager
    fieldsRegistered: 'ಜಮೀನುಗಳು ನೋಂದಾಯಿಸಲಾಗಿದೆ',
    drawNewField: 'ಹೊಸ ಜಮೀನಿನ ಗಡಿ ಗುರುತಿಸಿ',
    noFieldsYet: 'ಇನ್ನೂ ಯಾವುದೇ ಜಮೀನು ನೋಂದಾಯಿಸಿಲ್ಲ',
    noFieldsDesc: 'ಮೇಲೆ "ಹೊಸ ಜಮೀನಿನ ಗಡಿ ಗುರುತಿಸಿ" ಕ್ಲಿಕ್ ಮಾಡಿ ನಕ್ಷೆಯಲ್ಲಿ ಬಿಡಿಸಿ',
    totalArea: 'ಒಟ್ಟು ವಿಸ್ತೀರ್ಣ',
    avgNdvi: 'ಸರಾಸರಿ NDVI',
    fieldsCount: 'ಒಟ್ಟು ಜಮೀನುಗಳು',
    statusStressed: 'ಒತ್ತಡದಲ್ಲಿದೆ',
    statusModerate: 'ಮಧ್ಯಮ',
    statusHealthy: 'ಆರೋಗ್ಯಕರ',
    statusExcellent: 'ಅತ್ಯುತ್ತಮ',
    statusNoData: 'ಮಾಹಿತಿ ಇಲ್ಲ',
    sownOn: 'ಬಿತ್ತನೆ',

    // Crop Doctor Page
    cropDoctorTitle: '🔬 AI ಬೆಳೆ ವೈದ್ಯ ಮತ್ತು ರೋಗ ನಿರ್ಣಯ ಕೇಂದ್ರ',
    cropDoctorSubtitle: 'ರೋಗ ಪತ್ತೆ, ಆರೋಗ್ಯ ಸ್ಕೋರ್, NPK ಗೊಬ್ಬರ ಪ್ರಮಾಣ ಮತ್ತು ಬೆಳೆ ಸೂಕ್ತತೆಗಾಗಿ ಎಲೆಯ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    uploadPhotoBtn: 'ಎಲೆಯ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    leafScannerTitle: 'ಎಲೆ ಸ್ಕ್ಯಾನರ್',
    noImageLoaded: 'ಯಾವುದೇ ಚಿತ್ರ ಲೋಡ್ ಆಗಿಲ್ಲ',
    noImageDesc: 'ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಕೆಳಗಿನ ಮಾದರಿ ಆಯ್ಕೆಮಾಡಿ ಅಥವಾ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    dropzoneTitle: 'ಇಲ್ಲಿ ಎಲೆಯ ಫೋಟೋ ಹಾಕಿ ಅಥವಾ ಆಯ್ಕೆ ಮಾಡಿ',
    dropzoneSub: 'PNG, JPG, WEBP, HEIC ಫಾರ್ಮ್ಯಾಟ್‌ಗಳು ಬೆಂಬಲಿತವಾಗಿದೆ',
    samplePresetsTitle: '🧪 ಮಾದರಿ ಎಲೆಗಳನ್ನು ಪರೀಕ್ಷಿಸಿ',
    sampleRice: '🌾 ಭತ್ತದ ಬೆಂಕಿ ರೋಗ (Leaf Blast)',
    sampleWheat: '🍂 ಗೋಧಿಯ ಹಳದಿ ತುಕ್ಕು ರೋಗ (Yellow Rust)',
    sampleCorn: '🐛 ಜೋಳದ ಕಾಂಡ ಕೊರಕ (Stem Borer)',
    sampleSugarcane: '🌱 ಆರೋಗ್ಯಕರ ಕಬ್ಬು (Healthy)',
    emptyRevealTitle: 'ರೋಗ ವಿಶ್ಲೇಷಣೆ ನೋಡಲು ಎಲೆಯ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    emptyRevealDesc: 'ಎಡಭಾಗದಲ್ಲಿ ಎಲೆಯ ಫೋಟೋ ಆಯ್ಕೆಮಾಡಿ. ಅಗ್ರೋವಿಷನ್ AI ಎಲೆಯ ಆರೋಗ್ಯ ಸ್ಕೋರ್, ರೋಗದ ಹೆಸರು ಮತ್ತು NPK ಗೊಬ್ಬರದ ಸಲಹೆ ನೀಡುತ್ತದೆ.',
    selectFileToScan: 'ಫೋಟೋ ಆಯ್ಕೆಮಾಡಿ',
    pathogenResultTitle: 'ರೋಗ ನಿರ್ಣಯ ಫಲಿತಾಂಶ',
    cropHealthIndex: 'ಬೆಳೆ ಆರೋಗ್ಯ ಸೂಚ್ಯಂಕ',
    diagnosisConfidence: 'ನಿರ್ಣಯ ನಿಖರತೆ',
    affectedLeafArea: 'ಬಾಧಿತ ಎಲೆ ಪ್ರದೇಶ',
    symptomsObserved: 'ಕಂಡುಬಂದ ಲಕ್ಷಣಗಳು',
    npkGuideTitle: 'ಶಿಫಾರಸು ಮಾಡಿದ ರಸಗೊಬ್ಬರ ಮತ್ತು NPK ಪೋಷಕಾಂಶ ಗೈಡ್',
    npkTarget: 'NPK ಪ್ರಮಾಣ ಗುರಿ',
    soilGuideTitle: 'ಮಣ್ಣು, ಹವಾಮಾನ ಮತ್ತು ಸೂಕ್ತ ಪ್ರದೇಶ ಗೈಡ್',
    idealSoilPh: '🌱 ಸೂಕ್ತ ಮಣ್ಣು ಮತ್ತು pH ಪ್ರಮಾಣ',
    tempRainfall: '🌤️ ತಾಪಮಾನ ಮತ್ತು ಮಳೆ',
    optimalPh: 'ಸೂಕ್ತ ಮಣ್ಣಿನ pH',
    annualRainfall: 'ವಾರ್ಷಿಕ ಮಳೆ',
    growingRegions: '📍 ಭಾರತದ ಪ್ರಮುಖ ಬೆಳೆಯುವ ಪ್ರದೇಶಗಳು:',
    carePlanTitle: 'ಶಿಫಾರಸು ಮಾಡಿದ ಚಿಕಿತ್ಸೆ ಮತ್ತು ಆರೈಕೆ ಯೋಜನೆ',
    organicRemedy: '🌿 ಸಾವಯವ ಉಪಚಾರ (Organic)',
    chemicalTreatment: '🧪 ರಾಸಾಯನಿಕ ಉಪಚಾರ (Chemical)',

    // Save field modal
    saveFieldTitle: '🌾 ಹೊಸ ಜಮೀನು ಉಳಿಸಿ',
    fieldNameLabel: 'ಜಮೀನಿನ ಹೆಸರು *',
    cropTypeLabel: 'ಬೆಳೆಯ ವಿಧ',
    sowingDateLabel: 'ಬಿತ್ತನೆ ದಿನಾಂಕ',
    areaLabel: 'ವಿಸ್ತೀರ್ಣ (ಹೆಕ್ಟೇರ್)',
    saveBtn: '✓ ಜಮೀನು ಉಳಿಸಿ',
    cancelBtn: 'ರದ್ದುಗೊಳಿಸಿ',

    // Farmer Guide
    guideTitle: '📖 ಅಗ್ರೋವಿಷನ್ ಹೇಗೆ ಬಳಸುವುದು — ರೈತ ಮಾರ್ಗದರ್ಶಿ',
    guideSubtitle: 'ಉಪಗ್ರಹ ತಂತ್ರಜ್ಞಾನ ಬಳಸಿ ನಿಮ್ಮ ಬೆಳೆ ನಿಗಾ ವಹಿಸಲು ಈ ಸರಳ ಹಂತಗಳನ್ನು ಅನುಸರಿಸಿ',
    guideStep1Title: '1. ನಕ್ಷೆಯಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ',
    guideStep1Desc: 'ಯಾವುದೇ ಸ್ಥಳದಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ — NDVI ಹಸಿರು ಮಟ್ಟ, ತಾಪಮಾನ, ಮಣ್ಣಿನ ತೇವಾಂಶ ಮತ್ತು ಮಳೆ ಮಾಹಿತಿ ತಕ್ಷಣ ಪಡೆಯಿರಿ.',
    guideStep2Title: '2. ನಿಮ್ಮ ಜಮೀನು ಗುರುತಿಸಿ',
    guideStep2Desc: 'ಜಮೀನು ನಿರ್ವಾಹಕ → ಹೊಸ ಜಮೀನಿನ ಗಡಿ ಗುರುತಿಸಿ ಕ್ಲಿಕ್ ಮಾಡಿ ಮತ್ತು ನಕ್ಷೆಯಲ್ಲಿ ಗಡಿ ಬಿಡಿಸಿ.',
    guideStep3Title: '3. NDVI ಮೌಲ್ಯ ಓದಿ',
    guideStep3Desc: 'NDVI 0.6–1.0 = ಆರೋಗ್ಯಕರ ಬೆಳೆ। 0.2–0.5 = ಮಧ್ಯಮ। 0.2 ಕ್ಕಿಂತ ಕಡಿಮೆ = ಕಳಪೆ ಸಸ್ಯಾವರಣ ಅಥವಾ ಬರಿದಾದ ಮಣ್ಣು.',
    guideStep4Title: '4. ಎಲೆಯ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    guideStep4Desc: 'AI ಬೆಳೆ ವೈದ್ಯ ಟ್ಯಾಬ್‌ಗೆ ಹೋಗಿ ರೋಗಗ್ರಸ್ತ ಎಲೆಯ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. AI ರೋಗ ಪತ್ತೆ ಮಾಡಿ ಸಾವಯವ ಮತ್ತು ರಾಸಾಯನಿಕ ಪರಿಹಾರ ಸೂಚಿಸುತ್ತದೆ.',
    guideStep5Title: '5. ಬೆಳೆ ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    guideStep5Desc: 'ಸ್ಕ್ಯಾನ್ ನಂತರ ಬೆಳೆ ವರದಿ ಕ್ಲಿಕ್ ಮಾಡಿ NDVI, ಮಣ್ಣು, ಹವಾಮಾನ ಮತ್ತು ಶಿಫಾರಸುಗಳ PDF ವರದಿ ಪಡೆಯಿರಿ.',
    guideStep6Title: '6. ಭಾಷೆ ಬದಲಿಸಿ',
    guideStep6Desc: 'ಮೇಲೆ ಭಾಷಾ ಬಟನ್ ಒತ್ತಿ ಕನ್ನಡ, ಹಿಂದಿ, ತೆಲುಗು, ತಮಿಳು, ಮರಾಠಿ, ಪಂಜಾಬಿ ಅಥವಾ ಬಂಗಾಳಿಯಲ್ಲಿ ಓದಿ.',
    guideTip: '💡 ಸಲಹೆ: ಬೆಳೆ ಋತುವಿನಲ್ಲಿ ಪ್ರತಿ ವಾರ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ — ಸಮಸ್ಯೆಗಳನ್ನು ಬೇಗ ಪತ್ತೆ ಮಾಡಿ!',
  },

  te: {
    // Nav & General
    appTitle: 'అగ్రోవిజన్',
    subtitle: 'శాటిలైట్ ఇంటెలిజెన్స్',
    liveMap: '🛰️ లైవ్ శాటిలైట్ మ్యాప్',
    fieldManager: '🌾 పొలం మేనేజర్',
    cropDoctor: '🔬 AI పంట డాక్టర్',
    quickGuide: '📖 త్వరిత మార్గదర్శి',
    street: 'వీధి',
    satellite: 'శాటిలైట్',
    cropReport: 'పంట నివేదిక',
    downloading: 'నివేదిక సిద్ధమవుతోంది...',
    live: 'లైవ్',
    offline: 'ఆఫ్‌లైన్',
    logout: 'లాగౌట్',
    guest: 'అతిథి',

    // Dashboard HUD
    dashboardHeader: '🌾 పొలం సమాచార డాష్‌బోర్డ్',
    dashboardSubtitle: 'స్కాన్ చేయడానికి మ్యాప్‌పై క్లిక్ చేయండి · పొలాన్ని సేవ్ చేయడానికి హద్దులు గీయండి',
    scanning: 'స్కాన్ చేస్తోంది...',
    sysNominal: 'సిస్టమ్: సాధారణం',
    telemetryTitle: '📊 టెలిమెట్రీ & విశ్లేషణ',
    primaryScan: 'ప్రాథమిక స్కాన్ (NDVI)',
    sessionMetrics: 'సెషన్ కొలతలు',
    scanHistory: 'స్కాన్ చరిత్ర',

    // Field Manager
    fieldsRegistered: 'పొలాలు నమోదయ్యాయి',
    drawNewField: 'కొత్త పొలం హద్దులు గీయండి',
    noFieldsYet: 'ఇంకా పొలాలు నమోదు కాలేదు',
    noFieldsDesc: 'పైన "కొత్త పొలం హద్దులు గీయండి" క్లిక్ చేసి మ్యాప్‌పై గీయండి',
    totalArea: 'మొత్తం విస్తీర్ణం',
    avgNdvi: 'సగటు NDVI',
    fieldsCount: 'మొత్తం పొలాలు',
    statusStressed: 'ఒత్తిడిలో ఉంది',
    statusModerate: 'మధ్యస్థం',
    statusHealthy: 'ఆరోగ్యకరం',
    statusExcellent: 'అత్యుత్తమం',
    statusNoData: 'డేటా లేదు',
    sownOn: 'విత్తిన తేది',

    // Crop Doctor Page
    cropDoctorTitle: '🔬 AI పంట డాక్టర్ & తెగుళ్ల నిర్ధారణ కేంద్రం',
    cropDoctorSubtitle: 'తెగుళ్ల నిర్ధారణ, ఆరోగ్య స్కోరు, NPK ఎరువుల మోతాదు కోసం ఆకు ఫోటో అప్‌లోడ్ చేయండి.',
    uploadPhotoBtn: 'ఆకు ఫోటో అప్‌లోడ్ చేయండి',
    leafScannerTitle: 'ఆకు స్కానర్',
    noImageLoaded: 'ఫోటో లోడ్ కాలేదు',
    noImageDesc: 'విశ్లేషణ కోసం కింద నమూనా ఎంచుకోండి లేదా ఫోటో అప్‌లోడ్ చేయండి.',
    dropzoneTitle: 'ఇక్కడ ఆకు ఫోటో వేయండి లేదా ఎంచుకోండి',
    dropzoneSub: 'PNG, JPG, WEBP, HEIC సపోర్ట్ చేస్తుంది',
    samplePresetsTitle: '🧪 నమూనా ఆకులను పరీక్షించండి',
    sampleRice: '🌾 వరి అగ్గి తెగులు (Leaf Blast)',
    sampleWheat: '🍂 గోధుమ పసుపు కుంకుమ తెగులు (Yellow Rust)',
    sampleCorn: '🐛 జొన్న తొలుచు పురుగు (Stem Borer)',
    sampleSugarcane: '🌱 ఆరోగ్యకరమైన చెరకు (Healthy)',
    emptyRevealTitle: 'తెగుళ్ల విశ్లేషణ చూడటానికి ఆకు ఫోటో అప్‌లోడ్ చేయండి',
    emptyRevealDesc: 'ఎడమ వైపున ఆకు ఫోటో ఎంచుకోండి. అగ్రోవిజన్ AI ఆరోగ్య స్కోరు, తెగులు పేరు మరియు NPK ఎరువుల మోతాదు అందిస్తుంది.',
    selectFileToScan: 'ఫోటో ఎంచుకోండి',
    pathogenResultTitle: 'తెగులు నిర్ధారణ ఫలితం',
    cropHealthIndex: 'పంట ఆరోగ్య సూచిక',
    diagnosisConfidence: 'నిర్ధారణ కచ్చితత్వం',
    affectedLeafArea: 'బాధిత ఆకు విస్తీర్ణం',
    symptomsObserved: 'గమనించిన లక్షణాలు',
    npkGuideTitle: 'ఎరువులు & NPK పోషకాల గైడ్',
    npkTarget: 'NPK మోతాదు లక్ష్యం',
    soilGuideTitle: 'నేల, వాతావరణం & అనుకూల ప్రాంతాల గైడ్',
    idealSoilPh: '🌱 అనుకూల నేల & pH పరిమితి',
    tempRainfall: '🌤️ ఉష్ణోగ్రత & వర్షపాతం',
    optimalPh: 'అనుకూల నేల pH',
    annualRainfall: 'వార్షిక వర్షపాతం',
    growingRegions: '📍 భారతదేశంలో ప్రధాన అనుకూల ప్రాంతాలు:',
    carePlanTitle: 'సిఫార్సు చేసిన నివారణ చర్యలు',
    organicRemedy: '🌿 సేంద్రీయ నివారణ (Organic)',
    chemicalTreatment: '🧪 రసాయన నివారణ (Chemical)',

    // Save field modal
    saveFieldTitle: '🌾 కొత్త పొలాన్ని సేవ్ చేయండి',
    fieldNameLabel: 'పొలం పేరు *',
    cropTypeLabel: 'పంట రకం',
    sowingDateLabel: 'విత్తిన తేది',
    areaLabel: 'విస్తీర్ణం (హెక్టార్లు)',
    saveBtn: '✓ పొలాన్ని సేవ్ చేయి',
    cancelBtn: 'రద్దు చేయి',

    // Farmer Guide
    guideTitle: '📖 అగ్రోవిజన్ ఎలా ఉపయోగించాలి — రైతు మార్గదర్శి',
    guideSubtitle: 'ఉపగ్రహ సాంకేతికత ద్వారా మీ పంట పర్యవేక్షించడానికి ఈ సులభ దశలు అనుసరించండి',
    guideStep1Title: '1. మ్యాప్‌పై క్లిక్ చేయండి',
    guideStep1Desc: 'ఏ స్థానంలోనైనా క్లిక్ చేయండి — NDVI పచ్చదనం, ఉష్ణోగ్రత, నేల తేమ మరియు వర్షపాతం తక్షణ సమాచారం పొందండి.',
    guideStep2Title: '2. మీ పొలం గుర్తించండి',
    guideStep2Desc: 'పొలం మేనేజర్ → కొత్త పొలం హద్దులు గీయండి క్లిక్ చేసి మ్యాప్‌పై పొలం సరిహద్దు గీయండి.',
    guideStep3Title: '3. NDVI విలువ చదవండి',
    guideStep3Desc: 'NDVI 0.6–1.0 = ఆరోగ్యకరమైన పంట. 0.2–0.5 = మధ్యస్థం. 0.2 కంటే తక్కువ = బలహీనమైన వృక్షసంపద.',
    guideStep4Title: '4. ఆకు ఫోటో అప్‌లోడ్ చేయండి',
    guideStep4Desc: 'AI పంట డాక్టర్ ట్యాబ్‌కు వెళ్ళి జబ్బుపడిన ఆకు ఫోటో అప్‌లోడ్ చేయండి. AI వ్యాధి గుర్తించి నివారణలు సూచిస్తుంది.',
    guideStep5Title: '5. పంట నివేదిక డౌన్‌లోడ్ చేయండి',
    guideStep5Desc: 'స్కాన్ తర్వాత పంట నివేదిక క్లిక్ చేసి NDVI, నేల, వాతావరణం మరియు సిఫార్సులతో PDF పొందండి.',
    guideStep6Title: '6. భాష మార్చండి',
    guideStep6Desc: 'పైన భాష బటన్ నొక్కి తెలుగు, హిందీ, కన్నడ, తమిళం, మరాఠీ, పంజాబీ లేదా బెంగాలీలో చదవండి.',
    guideTip: '💡 చిట్కా: పంట సీజన్‌లో ప్రతి వారం స్కాన్ చేయండి — సమస్యలు త్వరగా పట్టుకోండి!',
  },

  ta: {
    // Nav & General
    appTitle: 'அக்ரோவிஷன்',
    subtitle: 'செயற்கைக்கோள் நுண்ணறிவு',
    liveMap: '🛰️ நேரலை செயற்கைக்கோள் வரைபடம்',
    fieldManager: '🌾 பண்ணை மேலாளர்',
    cropDoctor: '🔬 AI பயிர் மருத்துவர்',
    quickGuide: '📖 விரைவு வழிகாட்டி',
    street: 'தெரு',
    satellite: 'செயற்கைக்கோள்',
    cropReport: 'பயிர் அறிக்கை',
    downloading: 'அறிக்கை தயாராகிறது...',
    live: 'லைவ்',
    offline: 'ஆஃப்லைன்',
    logout: 'வெளியேறு',
    guest: 'விருந்தினர்',

    // Dashboard HUD
    dashboardHeader: '🌾 பண்ணை தகவல் டாஷ்போர்டு',
    dashboardSubtitle: 'ஸ்கேன் செய்ய வரைபடத்தில் கிளிக் செய்யவும் · நிலத்தை சேமிக்க எல்லை வரையவும்',
    scanning: 'ஸ்கேன் செய்யப்படுகிறது...',
    sysNominal: 'அமைப்பு: இயல்பு',
    telemetryTitle: '📊 தொலைஅளவியல் & பகுப்பாய்வு',
    primaryScan: 'முதன்மை ஸ்கேன் (NDVI)',
    sessionMetrics: 'அமர்வு அளவீடுகள்',
    scanHistory: 'ஸ்கேன் வரலாறு',

    // Field Manager
    fieldsRegistered: 'நிலங்கள் பதிவு செய்யப்பட்டுள்ளன',
    drawNewField: 'புதிய நில எல்லை வரையவும்',
    noFieldsYet: 'இன்னும் நிலங்கள் பதிவு செய்யப்படவில்லை',
    noFieldsDesc: 'மேலே உள்ள "புதிய நில எல்லை வரையவும்" கிளிக் செய்து வரைபடத்தில் வரையவும்',
    totalArea: 'மொத்த பரப்பு',
    avgNdvi: 'சராசரி NDVI',
    fieldsCount: 'மொத்த நிலங்கள்',
    statusStressed: 'பாதிக்கப்பட்டது',
    statusModerate: 'மிதமான',
    statusHealthy: 'ஆரோக்கியமானது',
    statusExcellent: 'மிகச்சிறந்தது',
    statusNoData: 'தரவு இல்லை',
    sownOn: 'விதைத்த நாள்',

    // Crop Doctor Page
    cropDoctorTitle: '🔬 AI பயிர் மருத்துவர் & நோய் கண்டறிதல் மையம்',
    cropDoctorSubtitle: 'நோய் கண்டறிதல், ஆரோக்கிய மதிப்பெண், NPK உரம் அளவுகளுக்கு இலையின் புகைப்படத்தைப் பதிவேற்றவும்.',
    uploadPhotoBtn: 'இலை புகைப்படத்தைப் பதிவேற்றவும்',
    leafScannerTitle: 'இலை ஸ்கேனர்',
    noImageLoaded: 'படம் ஏற்றப்படவில்லை',
    noImageDesc: 'பகுப்பாய்வுக்குக் கீழே உள்ள மாதிரியைத் தேர்ந்தெடுக்கவும் அல்லது புகைப்படத்தைப் பதிவேற்றவும்.',
    dropzoneTitle: 'இங்கு இலை புகைப்படத்தைப் போடவும் அல்லது தேர்ந்தெடுக்கவும்',
    dropzoneSub: 'PNG, JPG, WEBP, HEIC வடிவங்கள் ஆதரிக்கப்படுகின்றன',
    samplePresetsTitle: '🧪 மாதிரி இலைகளைச் சோதிக்கவும்',
    sampleRice: '🌾 நெல் குலை நோய் (Leaf Blast)',
    sampleWheat: '🍂 கோதுமை மஞ்சள் துரு நோய் (Yellow Rust)',
    sampleCorn: '🐛 சோளத் தண்டு துளைப்பான் (Stem Borer)',
    sampleSugarcane: '🌱 ஆரோக்கியமான கரும்பு (Healthy)',
    emptyRevealTitle: 'நோய் பகுப்பாய்வைக் காண இலையின் புகைப்படத்தைப் பதிவேற்றவும்',
    emptyRevealDesc: 'இடதுபுறத்தில் இலை புகைப்படத்தைத் தேர்ந்தெடுக்கவும். அக்ரோவிஷன் AI இலையின் ஆரோக்கிய மதிப்பெண், நோய் பெயர் மற்றும் NPK உரப் பரிந்துரைகளை வழங்கும்.',
    selectFileToScan: 'புகைப்படத்தைத் தேர்ந்தெடுக்கவும்',
    pathogenResultTitle: 'நோய் கண்டறிதல் முடிவு',
    cropHealthIndex: 'பயிர் ஆரோக்கிய குறியீடு',
    diagnosisConfidence: 'கண்டறிதல் துல்லியம்',
    affectedLeafArea: 'பாதிக்கப்பட்ட இலை பரப்பு',
    symptomsObserved: 'கண்டறியப்பட்ட அறிகுறிகள்',
    npkGuideTitle: 'பரிந்துரைக்கப்பட்ட உரங்கள் & NPK ஊட்டச்சத்து வழிகாட்டி',
    npkTarget: 'NPK இலக்கு அளவு',
    soilGuideTitle: 'மண், தட்பவெப்பநிலை & பொருத்தமான பகுதி வழிகாட்டி',
    idealSoilPh: '🌱 சிறந்த மண் & pH அளவு',
    tempRainfall: '🌤️ வெப்பநிலை & மழைப்பொழிவு',
    optimalPh: 'சிறந்த மண் pH',
    annualRainfall: 'ஆண்டு மழைப்பொழிவு',
    growingRegions: '📍 இந்தியாவில் முக்கியமான வளரும் பகுதிகள்:',
    carePlanTitle: 'பரிந்துரைக்கப்பட்ட சிகிச்சை & பராமரிப்பு திட்டம்',
    organicRemedy: '🌿 இயற்கை மருத்துவம் (Organic)',
    chemicalTreatment: '🧪 ரசாயன மருத்துவம் (Chemical)',

    // Save field modal
    saveFieldTitle: '🌾 புதிய நிலத்தைச் சேமிக்கவும்',
    fieldNameLabel: 'நிலத்தின் பெயர் *',
    cropTypeLabel: 'பயிர் வகை',
    sowingDateLabel: 'விதைத்த தேதி',
    areaLabel: 'பரப்பளவு (ஹெக்டேர்)',
    saveBtn: '✓ நிலத்தைச் சேமி',
    cancelBtn: 'ரத்து செய்',

    // Farmer Guide
    guideTitle: '📖 அக்ரோவிஷன் எப்படி பயன்படுத்துவது — விவசாயி வழிகாட்டி',
    guideSubtitle: 'செயற்கைக்கோள் தொழில்நுட்பம் மூலம் உங்கள் பயிரை கண்காணிக்க இந்த எளிய படிகளைப் பின்பற்றவும்',
    guideStep1Title: '1. வரைபடத்தில் கிளிக் செய்யவும்',
    guideStep1Desc: 'எந்த இடத்திலும் கிளிக் செய்யவும் — NDVI பச்சை தரவு, வெப்பநிலை, மண் ஈரப்பதம் மற்றும் மழைப்பொழிவு தகவல்கள் உடனடியாக பெறலாம்.',
    guideStep2Title: '2. உங்கள் நிலத்தை குறிக்கவும்',
    guideStep2Desc: 'பண்ணை மேலாளர் → புதிய நில எல்லை வரையவும் கிளிக் செய்து வரைபடத்தில் நிலத்தின் எல்லை வரையவும்.',
    guideStep3Title: '3. NDVI மதிப்பை படிக்கவும்',
    guideStep3Desc: 'NDVI 0.6–1.0 = ஆரோக்கியமான பயிர். 0.2–0.5 = மிதமான. 0.2 கீழே = மோசமான தாவர வளர்ச்சி.',
    guideStep4Title: '4. இலை புகைப்படம் பதிவேற்றவும்',
    guideStep4Desc: 'AI பயிர் மருத்துவர் தாவலுக்கு சென்று நோய்வாய்ப்பட்ட இலையின் புகைப்படம் பதிவேற்றவும். AI நோயை கண்டறிந்து தீர்வுகள் பரிந்துரைக்கும்.',
    guideStep5Title: '5. பயிர் அறிக்கை பதிவிறக்கவும்',
    guideStep5Desc: 'ஸ்கேன் செய்த பிறகு பயிர் அறிக்கை கிளிக் செய்து NDVI, மண், வானிலை மற்றும் பரிந்துரைகள் கொண்ட PDF பெறவும்.',
    guideStep6Title: '6. மொழியை மாற்றவும்',
    guideStep6Desc: 'மேலே மொழி பொத்தானை அழுத்தி தமிழ், இந்தி, கன்னடம், தெலுங்கு, மராத்தி, பஞ்சாபி அல்லது வங்காளத்தில் படிக்கவும்.',
    guideTip: '💡 குறிப்பு: பயிர் பருவத்தில் ஒவ்வொரு வாரமும் ஸ்கேன் செய்யுங்கள் — சிக்கல்களை முன்கூட்டியே கண்டுபிடிக்கலாம்!',
  },

  mr: {
    // Nav & General
    appTitle: 'ॲग्रोव्हिजन',
    subtitle: 'सॅटेलाइट इंटेलिजन्स',
    liveMap: '🛰️ लाईव्ह सॅटेलाइट नकाशा',
    fieldManager: '🌾 शेत व्यवस्थापक',
    cropDoctor: '🔬 AI पीक डॉक्टर',
    quickGuide: '📖 जलद मार्गदर्शक',
    street: 'रस्ता',
    satellite: 'सॅटेलाइट',
    cropReport: 'पीक अहवाल',
    downloading: 'अहवाल तयार होत आहे...',
    live: 'लाईव्ह',
    offline: 'ऑफलाईन',
    logout: 'लॉगआउट',
    guest: 'पाहुणे',

    // Dashboard HUD
    dashboardHeader: '🌾 शेत माहिती डॅशबोर्ड',
    dashboardSubtitle: 'स्कॅन करण्यासाठी नकाशावर क्लिक करा · शेत जतन करण्यासाठी सीमा आखा',
    scanning: 'स्कॅन होत आहे...',
    sysNominal: 'सिस्टम: सामान्य',
    telemetryTitle: '📊 टेलिमेट्री आणि विश्लेषण',
    primaryScan: 'प्राथमिक स्कॅन (NDVI)',
    sessionMetrics: 'सत्र मूल्ये',
    scanHistory: 'स्कॅन इतिहास',

    // Field Manager
    fieldsRegistered: 'शेते नोंदणीकृत आहेत',
    drawNewField: 'नवीन शेताची सीमा आखा',
    noFieldsYet: 'अद्याप एकही शेत नोंदवलेले नाही',
    noFieldsDesc: 'वर "नवीन शेताची सीमा आखा" वर क्लिक करा आणि नकाशावर आखा',
    totalArea: 'एकूण क्षेत्रफळ',
    avgNdvi: 'सरासरी NDVI',
    fieldsCount: 'एकूण शेते',
    statusStressed: 'ताणतणावात',
    statusModerate: 'मध्यम',
    statusHealthy: 'निरोगी',
    statusExcellent: 'उत्कृष्ट',
    statusNoData: 'माहिती नाही',
    sownOn: 'पेरणी',

    // Crop Doctor Page
    cropDoctorTitle: '🔬 AI पीक डॉक्टर आणि रोग निदान केंद्र',
    cropDoctorSubtitle: 'रोग निदान, आरोग्य स्कोर, NPK खत मात्रा आणि पीक योग्यतेसाठी पानाचा फोटो अपलोड करा.',
    uploadPhotoBtn: 'पानाचा फोटो अपलोड करा',
    leafScannerTitle: 'पान स्कॅनर',
    noImageLoaded: 'कोणतीही इमेज लोड केली नाही',
    noImageDesc: 'विश्लेषणासाठी खालील नमुना निवडा किंवा फोटो अपलोड करा.',
    dropzoneTitle: 'येथे पिकाच्या पानाचा फोटो टाका किंवा निवडा',
    dropzoneSub: 'PNG, JPG, WEBP, HEIC फॉरमॅट समर्थित आहेत',
    samplePresetsTitle: '🧪 नमुना पाने तपासा',
    sampleRice: '🌾 तांदूळ करपा रोग (Leaf Blast)',
    sampleWheat: '🍂 गव्हाचा पिवळा तांबेरा (Yellow Rust)',
    sampleCorn: '🐛 मका खोड कीड (Stem Borer)',
    sampleSugarcane: '🌱 निरोगी ऊस (Healthy)',
    emptyRevealTitle: 'रोग विश्लेषण पाहण्यासाठी पानाचा फोटो अपलोड करा',
    emptyRevealDesc: 'डाव्या बाजूला फोटो निवडा. ॲग्रोव्हिजन AI पिकाचा आरोग्य स्कोर, रोगाचे नाव आणि NPK खत सल्ला देईल.',
    selectFileToScan: 'फोटो निवडा',
    pathogenResultTitle: 'रोग निदान निकाल',
    cropHealthIndex: 'पीक आरोग्य निर्देशांक',
    diagnosisConfidence: 'निदान अचूकता',
    affectedLeafArea: 'बाधित पान क्षेत्र',
    symptomsObserved: 'आढळून आलेली लक्षणे',
    npkGuideTitle: 'शिफारस केलेली खते आणि NPK पोषण मार्गदर्शक',
    npkTarget: 'NPK मात्रा लक्ष्य',
    soilGuideTitle: 'माती, हवामान आणि योग्य प्रदेश मार्गदर्शक',
    idealSoilPh: '🌱 योग्य माती आणि pH मर्यादा',
    tempRainfall: '🌤️ तापमान आणि पाऊस',
    optimalPh: 'योग्य माती pH',
    annualRainfall: 'वार्षिक पाऊस',
    growingRegions: '📍 भारतातील प्रमुख योग्य पीक क्षेत्रे:',
    carePlanTitle: 'शॉपिंग आणि काळजी योजना',
    organicRemedy: '🌿 सेंद्रिय उपाय (Organic)',
    chemicalTreatment: '🧪 रासायनिक उपाय (Chemical)',

    // Save field modal
    saveFieldTitle: '🌾 नवीन शेत जतन करा',
    fieldNameLabel: 'शेताचे नाव *',
    cropTypeLabel: 'पिकाचा प्रकार',
    sowingDateLabel: 'पेरणीची तारीख',
    areaLabel: 'क्षेत्रफळ (हेक्टर)',
    saveBtn: '✓ शेत जतन करा',
    cancelBtn: 'रद्द करा',

    // Farmer Guide
    guideTitle: '📖 ॲग्रोव्हिजन कसे वापरावे — शेतकरी मार्गदर्शिका',
    guideSubtitle: 'उपग्रह तंत्रज्ञान वापरून पिकावर नजर ठेवण्यासाठी या सोप्या पायऱ्या अनुसरा',
    guideStep1Title: '1. नकाशावर क्लिक करा',
    guideStep1Desc: 'कोणत्याही ठिकाणावर क्लिक करा — NDVI हिरवेपणा, तापमान, मातीची आर्द्रता आणि पाऊस माहिती तत्काळ मिळवा.',
    guideStep2Title: '2. आपले शेत नोंदवा',
    guideStep2Desc: 'शेत व्यवस्थापक → नवीन शेताची सीमा आखा वर क्लिक करा आणि नकाशावर शेताची सीमा रेखाटा.',
    guideStep3Title: '3. NDVI मूल्य वाचा',
    guideStep3Desc: 'NDVI 0.6–1.0 = निरोगी पीक. 0.2–0.5 = मध्यम. 0.2 पेक्षा कमी = कमकुवत वनस्पती किंवा उघडी माती.',
    guideStep4Title: '4. पानाचा फोटो अपलोड करा',
    guideStep4Desc: 'AI पीक डॉक्टर टॅबवर जा आणि आजारी पानाचा फोटो अपलोड करा. AI रोग शोधून जैविक व रासायनिक उपाय सुचवेल.',
    guideStep5Title: '5. पीक अहवाल डाउनलोड करा',
    guideStep5Desc: 'स्कॅननंतर पीक अहवाल क्लिक करा आणि NDVI, माती, हवामान व शिफारसींसह PDF मिळवा.',
    guideStep6Title: '6. भाषा बदला',
    guideStep6Desc: 'वरील भाषा बटण दाबा आणि मराठी, हिंदी, कन्नड, तेलुगू, तमिळ, पंजाबी किंवा बंगाली मध्ये वाचा.',
    guideTip: '💡 सूचना: पीक हंगामात दर आठवड्याला स्कॅन करा — समस्या लवकर ओळखता येतील!',
  },

  pa: {
    // Nav & General
    appTitle: 'ਐਗਰੋਵਿਜ਼ਨ',
    subtitle: 'ਸੈਟੇਲਾਈਟ ਇੰਟੈਲੀਜੈਂਸ',
    liveMap: '🛰️ ਲਾਈਵ ਸੈਟੇਲਾਈਟ ਨਕਸ਼ਾ',
    fieldManager: '🌾 ਖੇਤ ਮੈਨੇਜਰ',
    cropDoctor: '🔬 AI ਫਸਲ ਡਾਕਟਰ',
    quickGuide: '📖 ਤੁਰੰਤ ਗਾਈਡ',
    street: 'ਸੜਕ',
    satellite: 'ਸੈਟੇਲਾਈਟ',
    cropReport: 'ਫਸਲ ਰਿਪੋਰਟ',
    downloading: 'ਰਿਪੋਰਟ ਬਣ ਰਹੀ ਹੈ...',
    live: 'ਲਾਈਵ',
    offline: 'ਆਫਲਾਈਨ',
    logout: 'ਲੌਗਆਊਟ',
    guest: 'ਮਹਿਮਾਨ',

    // Dashboard HUD
    dashboardHeader: '🌾 ਖੇਤ ਸੂਚਨਾ ਡੈਸ਼ਬੋਰਡ',
    dashboardSubtitle: 'ਸਕੈਨ ਕਰਨ ਲਈ ਨਕਸ਼ੇ \'ਤੇ ਕਲਿੱਕ ਕਰੋ · ਖੇਤ ਸੰਭਾਲਣ ਲਈ ਸੀਮਾ ਬਣਾਓ',
    scanning: 'ਸਕੈਨ ਹੋ ਰਿਹਾ ਹੈ...',
    sysNominal: 'ਸਿਸਟਮ: ਆਮ',
    telemetryTitle: '📊 ਟੈਲੀਮੈਟਰੀ ਅਤੇ ਵਿਸ਼ਲੇਸ਼ਣ',
    primaryScan: 'ਪ੍ਰਾਇਮਰੀ ਸਕੈਨ (NDVI)',
    sessionMetrics: 'ਸੈਸ਼ਨ ਮਾਪਦੰਡ',
    scanHistory: 'ਸਕੈਨ ਇਤਿਹਾਸ',

    // Field Manager
    fieldsRegistered: 'ਖੇਤ ਰਜਿਸਟਰਡ ਹਨ',
    drawNewField: 'ਨਵਾਂ ਖੇਤ ਬਣਾਓ',
    noFieldsYet: 'ਅਜੇ ਕੋਈ ਖੇਤ ਰਜਿਸਟਰਡ ਨਹੀਂ',
    noFieldsDesc: 'ਉੱਪਰ "ਨਵਾਂ ਖੇਤ ਬਣਾਓ" \'ਤੇ ਕਲਿੱਕ ਕਰੋ ਅਤੇ ਨਕਸ਼ੇ \'ਤੇ ਸੀਮਾ ਬਣਾਓ',
    totalArea: 'ਕੁੱਲ ਖੇਤਰਫਲ',
    avgNdvi: 'ਔਸਤ NDVI',
    fieldsCount: 'ਕੁੱਲ ਖੇਤ',
    statusStressed: 'ਤਣਾਅਪੂਰਨ',
    statusModerate: 'ਦਰਮਿਆਨਾ',
    statusHealthy: 'ਸਿਹਤਮੰਦ',
    statusExcellent: 'ਬਹੁਤ ਵਧੀਆ',
    statusNoData: 'ਕੋਈ ਡਾਟਾ ਨਹੀਂ',
    sownOn: 'ਬੀਜਿਆ',

    // Crop Doctor Page
    cropDoctorTitle: '🔬 AI ਫਸਲ ਡਾਕਟਰ ਅਤੇ ਬੀਮਾਰੀ ਨਿਦਾਨ ਕੇਂਦਰ',
    cropDoctorSubtitle: 'ਬੀਮਾਰੀ ਦੀ ਪਛਾਣ, ਸਿਹਤ ਸਕੋਰ ਅਤੇ NPK ਖਾਦ ਦੀ ਮਾਤਰਾ ਲਈ ਪੱਤੇ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ।',
    uploadPhotoBtn: 'ਪੱਤੇ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ',
    leafScannerTitle: 'ਪੱਤਾ ਸਕੈਨਰ',
    noImageLoaded: 'ਕੋਈ ਫੋਟੋ ਲੋਡ ਨਹੀਂ ਹੋਈ',
    noImageDesc: 'ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਹੇਠਾਂ ਦਿੱਤਾ ਨਮੂਨਾ ਚੁਣੋ ਜਾਂ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ।',
    dropzoneTitle: 'ਇੱਥੇ ਪੱਤੇ ਦੀ ਫੋਟੋ ਪਾਓ ਜਾਂ ਚੁਣੋ',
    dropzoneSub: 'PNG, JPG, WEBP, HEIC ਸਪੋਰਟਿਡ ਹਨ',
    samplePresetsTitle: '🧪 ਨਮੂਨਾ ਪੱਤੇ ਚੈੱਕ ਕਰੋ',
    sampleRice: '🌾 ਝੋਨੇ ਦਾ ਬਲਾਸਟ ਰੋਗ (Leaf Blast)',
    sampleWheat: '🍂 ਕਣਕ ਦਾ ਪੀਲਾ ਕੁੰਗੀ ਰੋਗ (Yellow Rust)',
    sampleCorn: '🐛 ਮੱਕੀ ਦੀ ਸੁੰਡੀ (Stem Borer)',
    sampleSugarcane: '🌱 ਸਿਹਤਮੰਦ ਕਮਾਦ (Healthy)',
    emptyRevealTitle: 'ਬੀਮਾਰੀ ਦੀ ਰਿਪੋਰਟ ਦੇਖਣ ਲਈ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ',
    emptyRevealDesc: 'ਖੱਬੇ ਪਾਸੇ ਫੋਟੋ ਚੁਣੋ। ਐਗਰੋਵਿਜ਼ਨ AI ਫਸਲ ਦਾ ਸਿਹਤ ਸਕੋਰ, ਬੀਮਾਰੀ ਦਾ ਨਾਮ ਅਤੇ NPK ਖਾਦ ਦੀ ਸਲਾਹ ਦੇਵੇਗਾ।',
    selectFileToScan: 'ਫੋਟੋ ਚੁਣੋ',
    pathogenResultTitle: 'ਬੀਮਾਰੀ ਨਿਦਾਨ ਨਤੀਜਾ',
    cropHealthIndex: 'ਫਸਲ ਸਿਹਤ ਸੂਚਕਾਂਕ',
    diagnosisConfidence: 'ਨਿਦਾਨ ਸ਼ੁੱਧਤਾ',
    affectedLeafArea: 'ਪ੍ਰਭਾਵਿਤ ਪੱਤਾ ਖੇਤਰ',
    symptomsObserved: 'ਦੇਖੇ ਗਏ ਲੱਛਣ',
    npkGuideTitle: 'ਸਿਫਾਰਸ਼ ਕੀਤੀਆਂ ਖਾਦਾਂ ਅਤੇ NPK ਪੋਸ਼ਣ ਗਾਈਡ',
    npkTarget: 'NPK ਖਾਦ ਦੀ ਮਾਤਰਾ',
    soilGuideTitle: 'ਮਿੱਟੀ, ਜਲਵਾਯੂ ਅਤੇ ਢੁਕਵੇਂ ਖੇਤਰਾਂ ਦੀ ਗਾਈਡ',
    idealSoilPh: '🌱 ਢੁਕਵੀਂ ਮਿੱਟੀ ਅਤੇ pH ਸੀਮਾ',
    tempRainfall: '🌤️ ਤਾਪਮਾਨ ਅਤੇ ਮੀਂਹ',
    optimalPh: 'ਢੁਕਵੀਂ ਮਿੱਟੀ ਦਾ pH',
    annualRainfall: 'ਸਾਲਾਨਾ ਮੀਂਹ',
    growingRegions: '📍 ਭਾਰਤ ਦੇ ਪ੍ਰਮੁੱਖ ਢੁਕਵੇਂ ਖੇਤਰ:',
    carePlanTitle: 'ਸਿਫਾਰਸ਼ ਕੀਤਾ ਇਲਾਜ ਅਤੇ ਦੇਖਭਾਲ ਯੋਜਨਾ',
    organicRemedy: '🌿 ਦੇਸੀ/ਜੈਵਿਕ ਇਲਾਜ (Organic)',
    chemicalTreatment: '🧪 ਰਸਾਇਣਕ ਇਲਾਜ (Chemical)',

    // Save field modal
    saveFieldTitle: '🌾 ਨਵਾਂ ਖੇਤ ਸੰਭਾਲੋ',
    fieldNameLabel: 'ਖੇਤ ਦਾ ਨਾਮ *',
    cropTypeLabel: 'ਫਸਲ ਦੀ ਕਿਸਮ',
    sowingDateLabel: 'ਬੀਜਣ ਦੀ ਮਿਤੀ',
    areaLabel: 'ਖੇਤਰਫਲ (ਹੈਕਟੇਅਰ)',
    saveBtn: '✓ ਖੇਤ ਸੰਭਾਲੋ',
    cancelBtn: 'ਰੱਦ ਕਰੋ',

    // Farmer Guide
    guideTitle: '📖 ਐਗਰੋਵਿਜ਼ਨ ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ — ਕਿਸਾਨ ਗਾਈਡ',
    guideSubtitle: 'ਸੈਟੇਲਾਈਟ ਤਕਨੀਕ ਨਾਲ ਆਪਣੀ ਫਸਲ ਦੀ ਨਿਗਰਾਨੀ ਕਰਨ ਲਈ ਇਹ ਸਰਲ ਕਦਮ ਚੁੱਕੋ',
    guideStep1Title: '1. ਨਕਸ਼ੇ ਤੇ ਕਲਿੱਕ ਕਰੋ',
    guideStep1Desc: 'ਕਿਸੇ ਵੀ ਜਗ੍ਹਾ ਤੇ ਕਲਿੱਕ ਕਰੋ — NDVI ਹਰਿਆਵਲ, ਤਾਪਮਾਨ, ਮਿੱਟੀ ਦੀ ਨਮੀ ਅਤੇ ਬਾਰਿਸ਼ ਦੀ ਜਾਣਕਾਰੀ ਤੁਰੰਤ ਮਿਲੇਗੀ।',
    guideStep2Title: '2. ਆਪਣਾ ਖੇਤ ਬਣਾਓ',
    guideStep2Desc: 'ਖੇਤ ਮੈਨੇਜਰ → ਨਵਾਂ ਖੇਤ ਬਣਾਓ ਤੇ ਕਲਿੱਕ ਕਰੋ ਅਤੇ ਨਕਸ਼ੇ ਤੇ ਆਪਣੇ ਖੇਤ ਦੀ ਸੀਮਾ ਬਣਾਓ।',
    guideStep3Title: '3. NDVI ਮੁੱਲ ਪੜ੍ਹੋ',
    guideStep3Desc: 'NDVI 0.6–1.0 = ਸਿਹਤਮੰਦ ਫਸਲ. 0.2–0.5 = ਦਰਮਿਆਨੀ. 0.2 ਤੋਂ ਘੱਟ = ਕਮਜ਼ੋਰ ਬਨਸਪਤੀ ਜਾਂ ਨੰਗੀ ਮਿੱਟੀ।',
    guideStep4Title: '4. ਪੱਤੇ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ',
    guideStep4Desc: 'AI ਫਸਲ ਡਾਕਟਰ ਟੈਬ ਤੇ ਜਾਓ ਅਤੇ ਬਿਮਾਰ ਪੱਤੇ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ। AI ਬਿਮਾਰੀ ਦੱਸ ਕੇ ਦੇਸੀ ਅਤੇ ਰਸਾਇਣਕ ਇਲਾਜ ਦੱਸੇਗਾ।',
    guideStep5Title: '5. ਫਸਲ ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ',
    guideStep5Desc: 'ਸਕੈਨ ਤੋਂ ਬਾਅਦ ਫਸਲ ਰਿਪੋਰਟ ਤੇ ਕਲਿੱਕ ਕਰੋ ਅਤੇ NDVI, ਮਿੱਟੀ, ਮੌਸਮ ਅਤੇ ਸਲਾਹਾਂ ਵਾਲੀ PDF ਲਓ।',
    guideStep6Title: '6. ਭਾਸ਼ਾ ਬਦਲੋ',
    guideStep6Desc: 'ਉੱਪਰ ਭਾਸ਼ਾ ਬਟਨ ਦਬਾਓ ਅਤੇ ਪੰਜਾਬੀ, ਹਿੰਦੀ, ਕੰਨੜ, ਤੇਲੁਗੂ, ਤਮਿਲ, ਮਰਾਠੀ ਜਾਂ ਬੰਗਾਲੀ ਵਿੱਚ ਪੜ੍ਹੋ।',
    guideTip: '💡 ਸੁਝਾਅ: ਫਸਲ ਦੇ ਮੌਸਮ ਵਿੱਚ ਹਰ ਹਫ਼ਤੇ ਸਕੈਨ ਕਰੋ — ਸਮੱਸਿਆਵਾਂ ਜਲਦੀ ਫੜੀਆਂ ਜਾਣਗੀਆਂ!',
  },

  bn: {
    // Nav & General
    appTitle: 'অ্যাগ্রোভিশন',
    subtitle: 'স্যাটেলাইট ইন্টেলিজেন্স',
    liveMap: '🛰️ লাইভ স্যাটেলাইট ম্যাপ',
    fieldManager: '🌾 জমি ম্যানেজার',
    cropDoctor: '🔬 AI ফসল ডাক্তার',
    quickGuide: '📖 দ্রুত গাইড',
    street: 'রাস্তা',
    satellite: 'স্যাটেলাইট',
    cropReport: 'ফসলের রিপোর্ট',
    downloading: 'রিপোর্ট তৈরি হচ্ছে...',
    live: 'লাইভ',
    offline: 'অফলাইন',
    logout: 'লগআউট',
    guest: 'অতিথি',

    // Dashboard HUD
    dashboardHeader: '🌾 জমি তথ্য ড্যাশবোর্ড',
    dashboardSubtitle: 'স্ক্যান করতে মানচিত্রে ক্লিক করুন · জমি সংরক্ষণ করতে সীমানা আঁকুন',
    scanning: 'স্ক্যান করা হচ্ছে...',
    sysNominal: 'সিস্টেম: স্বাভাবিক',
    telemetryTitle: '📊 টেলিমেট্রি এবং বিশ্লেষণ',
    primaryScan: 'প্রাথমিক স্ক্যান (NDVI)',
    sessionMetrics: 'সেশনের পরিমাপ',
    scanHistory: 'স্ক্যান ইতিহাস',

    // Field Manager
    fieldsRegistered: 'টি জমি নিবন্ধিত',
    drawNewField: 'নতুন জমির সীমানা আঁকুন',
    noFieldsYet: 'এখনও কোনো জমি নিবন্ধিত হয়নি',
    noFieldsDesc: 'উপরে "নতুন জমির সীমানা আঁকুন" এ ক্লিক করুন এবং মানচিত্রে আঁকুন',
    totalArea: 'মোট ক্ষেত্রফল',
    avgNdvi: 'গড় NDVI',
    fieldsCount: 'মোট জমি',
    statusStressed: 'সংকটাপন্ন',
    statusModerate: 'মাঝারি',
    statusHealthy: 'স্বাস্থ্যকর',
    statusExcellent: 'চমৎকার',
    statusNoData: 'তথ্য নেই',
    sownOn: 'বপন',

    // Crop Doctor Page
    cropDoctorTitle: '🔬 AI ফসল ডাক্তার এবং রোগ নির্ণয় কেন্দ্র',
    cropDoctorSubtitle: 'রোগ নির্ণয়, স্বাস্থ্য স্কোর, NPK সার প্রয়োগের পরিমাণ এবং চাষের উপযোগীতার জন্য পাতার ছবি আপলোড করুন।',
    uploadPhotoBtn: 'পাতার ছবি আপলোড করুন',
    leafScannerTitle: 'পাতা স্ক্যানার',
    noImageLoaded: 'কোনো ছবি লোড হয়নি',
    noImageDesc: 'বিশ্লেষণের জন্য নিচে নমুনা বেছে নিন অথবা ছবি আপলোড করুন।',
    dropzoneTitle: 'এখানে পাতার ছবি ড্রপ করুন অথবা নির্বাচন করুন',
    dropzoneSub: 'PNG, JPG, WEBP, HEIC ফরম্যাট সমর্থিত',
    samplePresetsTitle: '🧪 নমুনা পাতা পরীক্ষা করুন',
    sampleRice: '🌾 ধানের ব্লাস্ট রোগ (Leaf Blast)',
    sampleWheat: '🍂 গমের হলুদ মরিচা রোগ (Yellow Rust)',
    sampleCorn: '🐛 ভূট্টার মাজরা পোকা (Stem Borer)',
    sampleSugarcane: '🌱 সুস্থ আখ (Healthy)',
    emptyRevealTitle: 'রোগ বিশ্লেষণ দেখতে পাতার ছবি আপলোড করুন',
    emptyRevealDesc: 'বাম পাশে পাতার ছবি আপলোড করুন। অ্যাগ্রোভিশন AI পাতার স্বাস্থ্য স্কোর, রোগের নাম এবং NPK সারের পরিমাণ পরামর্শ দেবে।',
    selectFileToScan: 'ছবি নির্বাচন করুন',
    pathogenResultTitle: 'রোগ নির্ণয়ের ফলাফল',
    cropHealthIndex: 'ফসলের স্বাস্থ্য সূচক',
    diagnosisConfidence: 'নির্ণয়ের নির্ভুলতা',
    affectedLeafArea: 'আক্রান্ত পাতার ক্ষেত্রফল',
    symptomsObserved: 'পর্যবেক্ষিত লক্ষণসমূহ',
    npkGuideTitle: 'সুপারিশকৃত সার এবং NPK পুষ্টি গাইড',
    npkTarget: 'NPK সারের লক্ষ্যমাত্রা',
    soilGuideTitle: 'মাটি, আবহাওয়া এবং উপযোগী অঞ্চলের গাইড',
    idealSoilPh: '🌱 আদর্শ মাটি এবং pH মাত্রা',
    tempRainfall: '🌤️ তাপমাত্রা এবং বৃষ্টিপাত',
    optimalPh: 'উপযোগী মাটির pH',
    annualRainfall: 'বার্ষিক বৃষ্টিপাত',
    growingRegions: '📍 ভারতের প্রধান প্রধান উপযোগী চাষ অঞ্চল:',
    carePlanTitle: 'সুপারিশকৃত চিকিৎসা ও পরিচর্যা পরিকল্পনা',
    organicRemedy: '🌿 জৈব প্রতিকার (Organic)',
    chemicalTreatment: '🧪 রাসায়নিক প্রতিকার (Chemical)',

    // Save field modal
    saveFieldTitle: '🌾 নতুন জমি সংরক্ষণ করুন',
    fieldNameLabel: 'জমির নাম *',
    cropTypeLabel: 'ফসলের ধরন',
    sowingDateLabel: 'বপনের তারিখ',
    areaLabel: 'ক্ষেত্রফল (হেক্টর)',
    saveBtn: '✓ জমি সংরক্ষণ করুন',
    cancelBtn: 'বাতিল করুন',

    // Farmer Guide
    guideTitle: '📖 অ্যাগ্রোভিশন কীভাবে ব্যবহার করবেন — কৃষক গাইড',
    guideSubtitle: 'স্যাটেলাইট প্রযুক্তি ব্যবহার করে আপনার ফসল পর্যবেক্ষণ করতে এই সহজ ধাপগুলো অনুসরণ করুন',
    guideStep1Title: '1. মানচিত্রে ক্লিক করুন',
    guideStep1Desc: 'যেকোনো জায়গায় ক্লিক করুন — NDVI সবুজ স্বাস্থ্য, তাপমাত্রা, মাটির আর্দ্রতা ও বৃষ্টিপাতের তথ্য তাৎক্ষণিক পান।',
    guideStep2Title: '2. আপনার জমি চিহ্নিত করুন',
    guideStep2Desc: 'জমি ম্যানেজার → নতুন জমির সীমানা আঁকুন ক্লিক করুন এবং মানচিত্রে জমির সীমানা আঁকুন।',
    guideStep3Title: '3. NDVI মান পড়ুন',
    guideStep3Desc: 'NDVI 0.6–1.0 = সুস্থ ফসল. 0.2–0.5 = মাঝারি. 0.2 এর নিচে = দুর্বল গাছপালা বা খালি মাটি।',
    guideStep4Title: '4. পাতার ছবি আপলোড করুন',
    guideStep4Desc: 'AI ফসল ডাক্তার ট্যাবে যান এবং অসুস্থ পাতার ছবি আপলোড করুন। AI রোগ শনাক্ত করে জৈব ও রাসায়নিক প্রতিকার দেবে।',
    guideStep5Title: '5. ফসলের রিপোর্ট ডাউনলোড করুন',
    guideStep5Desc: 'স্ক্যানের পর ফসলের রিপোর্ট ক্লিক করুন এবং NDVI, মাটি, আবহাওয়া ও সুপারিশসহ PDF পান।',
    guideStep6Title: '6. ভাষা পরিবর্তন করুন',
    guideStep6Desc: 'উপরে ভাষা বাটন চাপুন এবং বাংলা, হিন্দি, কন্নড, তেলুগু, তামিল, মারাঠি বা পাঞ্জাবিতে পড়ুন।',
    guideTip: '💡 টিপস: ফসলের মৌসুমে প্রতি সপ্তাহে স্ক্যান করুন — সমস্যা আগেভাগে ধরা পড়বে!',
  }
};

// ── Context Creation ────────────────────────────────────────────────────────
const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [langCode, setLangCode] = useState(() => {
    return localStorage.getItem('agro_lang') || 'en';
  });

  const changeLanguage = (code) => {
    setLangCode(code);
    localStorage.setItem('agro_lang', code);
  };

  const t = (key) => {
    const dict = TRANSLATIONS[langCode] || TRANSLATIONS['en'];
    return dict[key] || TRANSLATIONS['en'][key] || key;
  };

  const currentLangObj = LANGUAGES.find(l => l.code === langCode) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ langCode, setLangCode: changeLanguage, t, currentLangObj, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return ctx;
}
